### ISSUE TITLE
cpu governor not seem to work

### ISSUE THREAD

**Issue by MDCY9008** [hzyitc/armbian-onecloud#1]
```root@onecloud:~# systemctl status cpufrequtils
Jun 01 01:46:20 onecloud systemd[1]: Starting LSB: set CPUFreq kernel parameters...
Jun 01 01:46:20 onecloud cpufrequtils[662]:  * CPUFreq Utilities: Setting ondemand CPUFreq governor...
Jun 01 01:46:20 onecloud cpufrequtils[662]:  * disabled, governor not available...
Jun 01 01:46:20 onecloud cpufrequtils[662]:    ...done.
Jun 01 01:46:20 onecloud systemd[1]: Started LSB: set CPUFreq kernel parameters.
```
![~QGKY6DT9(EF2CPBCDBL~WN](https://user-images.githubusercontent.com/54255527/171315402-0411b8ca-98b9-4295-b0ae-a3091ade9744.png)

**Comment by hzyitc** [comment]
Did you use `edge` to test?

It may due to the lack of driver.

And the voltage of `Soc` is fixed at 1.0V in onecloud. I didn't find a adjustable power in the board.

**Comment by hzyitc** [comment]
Well, the  `dtb` you used probably comes from `ODROID C1` which has the same `SoC`.

`ODROID C1` has a adjustable power for `Soc`(Check Page 16 in the [Schematics](https://dn.odroid.com/S805/Schematics/odroid-c1+_rev0.4_20160226.pdf)). But `onecloud` only has some fixed powers.

And it seem that `Linux` use [OPP](https://docs.kernel.org/power/opp.html) to controll `voltage` and `frequency`.

So it may due to the fail to adjust the `voltage`.

**Comment by MDCY9008** [comment]
> Well, the `dtb` you used probably comes from `ODROID C1` which has the same `SoC`.
> 
> `ODROID C1` has a adjustable power for `Soc`(Check Page 16 in the [Schematics](https://dn.odroid.com/S805/Schematics/odroid-c1+_rev0.4_20160226.pdf)). But `onecloud` only has some fixed powers.
> 
> And it seem that `Linux` use [OPP](https://docs.kernel.org/power/opp.html) to controll `voltage` and `frequency`.
> 
> So it may due to the fail to adjust the `voltage`.

作者您好，这是之前有人为玩客云适配的代码，我看他的```patch```里有关于可调电压的设置，所以说玩客云是有可调电压的吧。
[https://github.com/Leo357449107/Build-Armbian/blob/master/patch/kernel/aml-s812-current/wky-patch.patch](url)

**Comment by hzyitc** [comment]
其实这个`dts`大部分都是来自`ODROID C1`的，你可以看看[ODROID C1的dts](https://github.com/xdarklight/linux/blob/master/arch/arm/boot/dts/meson8b-odroidc1.dts)。它的调压部分的全是`ODROID C1`的。

玩客云上的降压芯片我看了，是用电阻分压来调节的可调芯片，所以极大概率不支持pwm调压。

**Comment by hzyitc** [comment]
Solved.

Just remove `cpu-supply = <&vcc_core>;` in `dts`.

**Comment by MDCY9008** [comment]
> Solved.
> 
> Just remove `cpu-supply = <&vcc_core>;` in `dts`.

I tested it, but OneCloud won't start.
我试了一下，玩客云启动不了

**Comment by hzyitc** [comment]
哪个`分支`?我用`edge`测试的。

贴上`启动日志`看下吧

**Comment by MDCY9008** [comment]
> 哪个`分支`?我用`edge`测试的。
> 
> 贴上`启动日志`看下吧

release里最新的29 测试usb的包 edge jammy
能否发送一份修改过的```dts``` ```dtb```我想看看是不是我改错了

**Comment by hzyitc** [comment]
[freq branch](https://github.com/hzyitc/armbian-onecloud/commits/freq)

**Comment by MDCY9008** [comment]
> [freq branch](https://github.com/hzyitc/armbian-onecloud/commits/freq)

![image](https://user-images.githubusercontent.com/54255527/172380045-a3cd9e0c-04e5-4e5b-b961-25b8840a2e95.png)

**Comment by hzyitc** [comment]
看`output/debug/compilation.log `

不过大概率是缺libmpc-dev, 见[Compile error](https://github.com/hzyitc/armbian-onecloud#compile-error)

**Comment by MDCY9008** [comment]
> 看`output/debug/compilation.log `
> 
> 不过大概率是缺libmpc-dev, 见[Compile error](https://github.com/hzyitc/armbian-onecloud#compile-error)

我用的action编译的
![image](https://user-images.githubusercontent.com/54255527/172389822-2ee4b157-5a0c-47fd-9015-7e4d326cbf16.png)
https://github.com/MDCY9008/build 这是我使用的仓库，我只是把freq branch合入了而已

**Comment by MDCY9008** [comment]
> [freq branch](https://github.com/hzyitc/armbian-onecloud/commits/freq)

![image](https://user-images.githubusercontent.com/54255527/172394060-43cef559-202e-4f7e-aaa7-a957011859ef.png)

**Comment by hzyitc** [comment]
抱歉，由于`rebase`，生成的`patch`行数是错的，没注意到，稍等，我将重新`强制推送`

**Comment by MDCY9008** [comment]
> 已更新

仍然无法启动，红灯常亮，```1.0```的板子，用的首选底包，CPU都不发热 :(

**Comment by hzyitc** [comment]
连接`ttl`看`启动日志`吧。不然也没法分析

**Comment by MDCY9008** [comment]
> 连接`ttl`看`启动日志`吧。不然也没法分析

是这样打算的，但是要过几个星期才能分析了，TTL小板买了，上海这快递还没通  :(

**Comment by hzyitc** [comment]
Fix in [0cc91b7](https://github.com/hzyitc/armbian-onecloud/commit/0cc91b72300b17fc7f406b66165ca4aa5fe55d95)

**Comment by hzyitc** [comment]
该`issue`已被修复，先关了

无法启动的问题大概率跟该`issue`无关，如有需要请另开`issue`

**Comment by hzyitc** [comment]
还真是相关问题，`V1.0板子`的`CPU` 在 `1.5GHz` 时工作不稳定，故导致启动失败。
