### ISSUE TITLE
[转]玩客云刷完armbian后自身上传速度极低

### ISSUE THREAD

**Issue by golden777** [hzyitc/armbian-onecloud#100]
碰到了一样的问题,转过来请教

做旁路由时发现网速下降极为严重，于是用iperf3测了一下与局域网中另一台windows设备的通信速度发现当玩客云做客户端时，也就是上传时速度极低，自身做服务端，下载时速度倒是隐约能到千兆想问一下各位大佬这是我这台玩客云不太行了，还是说通病

https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8278491&extra=page%3D4&mobile=2

以上是转发,碰到了同样的问题,似乎用openwrt正常,请问能否把驱动替换换过来? 目前用一个USB网卡正常,但USB2.0速度较慢

**Comment by shao21104** [comment]
<img width="1095" alt="网速" src="https://user-images.githubusercontent.com/126444630/223699949-684f647c-c273-421b-a3cb-8785cd2d4864.png">

**Comment by hzyitc** [comment]
#2 

目前来看V1.0应该是正常的，V1.3可能有这个问题
