### ISSUE TITLE
玩客云 刷入armbian后  omv-extras 安装docker 失败

### ISSUE THREAD

**Issue by chenychong** [hzyitc/armbian-onecloud#102]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-installdocker docker install': Docker storage :: /var/lib/docker
Agent port:: 8000
Web port:: 9000
Yacht port:: 8001
ee:: 0
image:: portainer/portainer-ce
Enable TLS:: 0
arch :: armhf
option :: docker
state :: install
extras :: 6.1.1
DNS OK.
Create override directory ...
Create override file ...
mode of '/etc/systemd/system/docker.service.d/waitAllMounts.conf' changed from 0666 (rw-rw-rw-) to 0644 (rw-r--r--)
Reload systemd daemon ...
Get:1 file:/var/cache/openmediavault/archives InRelease
Ign:1 file:/var/cache/openmediavault/archives InRelease
Get:2 file:/var/cache/openmediavault/archives Release
Ign:2 file:/var/cache/openmediavault/archives Release
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Hit:6 http://deb.debian.org/debian bullseye InRelease
Hit:7 http://deb.debian.org/debian bullseye-updates InRelease
Get:8 http://security.debian.org/ bullseye-security InRelease [48.4 kB]
Hit:9 http://packages.openmediavault.org/public shaitan InRelease
Hit:10 https://download.docker.com/linux/debian bullseye InRelease
Hit:11 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease
Hit:13 https://openmediavault.github.io/packages shaitan InRelease
Hit:12 http://mirrors.tuna.tsinghua.edu.cn/armbian bullseye InRelease
Get:14 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Hit:15 http://httpredir.debian.org/debian bullseye-backports InRelease
Fetched 96.7 kB in 7s (13.3 kB/s)
Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
containerd.io docker-ce-cli
Suggested packages:
cgroupfs-mount | cgroup-lite
Recommended packages:
apparmor docker-ce-rootless-extras libltdl7 pigz docker-buildx-plugin
The following NEW packages will be installed:
containerd.io docker-ce docker-ce-cli docker-compose-plugin
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 55.4 MB of archives.
After this operation, 235 MB of additional disk space will be used.
Get:1 https://download.docker.com/linux/debian bullseye/stable armhf containerd.io armhf 1.6.18-1 [20.7 MB]
Get:2 https://download.docker.com/linux/debian bullseye/stable armhf docker-ce-cli armhf 5:23.0.1-1debian.11bullseye [12.0 MB]
Get:3 https://download.docker.com/linux/debian bullseye/stable armhf docker-ce armhf 5:23.0.1-1debian.11bullseye [13.9 MB]
Get:4 https://download.docker.com/linux/debian bullseye/stable armhf docker-compose-plugin armhf 2.16.0-1debian.11bullseye [8738 kB]
Fetched 55.4 MB in 13s (4286 kB/s)
Selecting previously unselected package containerd.io.
(Reading database ...
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 48067 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.6.18-1_armhf.deb ...
Unpacking containerd.io (1.6.18-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a23.0.1-1debian.11bullseye_armhf.deb ...
Unpacking docker-ce-cli (5:23.0.1-1debian.11bullseye) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a23.0.1-1debian.11bullseye_armhf.deb ...
Unpacking docker-ce (5:23.0.1-1debian.11bullseye) ...
Selecting previously unselected package docker-compose-plugin.
Preparing to unpack .../docker-compose-plugin_2.16.0-1debian.11bullseye_armhf.deb ...
Unpacking docker-compose-plugin (2.16.0-1debian.11bullseye) ...
Setting up containerd.io (1.6.18-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up docker-compose-plugin (2.16.0-1debian.11bullseye) ...
Setting up docker-ce-cli (5:23.0.1-1debian.11bullseye) ...
Setting up docker-ce (5:23.0.1-1debian.11bullseye) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/docker.service.d
└─waitAllMounts.conf
Active: activating (auto-restart) (Result: exit-code) since Sun 2023-03-12 21:29:10 CST; 37ms ago
TriggeredBy: ● docker.socket
Docs: https://docs.docker.com/
Process: 15309 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
Main PID: 15309 (code=exited, status=1/FAILURE)
CPU: 836ms
dpkg: error processing package docker-ce (--configure):
installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
docker-ce
Failed to install docker.
Try fixing install...
Reading package lists...

Building dependency tree...

Reading state information...

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up docker-ce (5:23.0.1-1debian.11bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/docker.service.d
└─waitAllMounts.conf
Active: activating (auto-restart) (Result: exit-code) since Sun 2023-03-12 21:30:04 CST; 39ms ago
TriggeredBy: ● docker.socket
Docs: https://docs.docker.com/
Process: 16637 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
Main PID: 16637 (code=exited, status=1/FAILURE)
CPU: 775ms
dpkg: error processing package docker-ce (--configure):
installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
docker-ce
Unable to fix docker install.

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-installdocker docker install': Docker storage :: /var/lib/docker
Agent port:: 8000
Web port:: 9000
Yacht port:: 8001
ee:: 0
image:: portainer/portainer-ce
Enable TLS:: 0
arch :: armhf
option :: docker
state :: install
extras :: 6.1.1
DNS OK.
Create override directory ...
Create override file ...
mode of '/etc/systemd/system/docker.service.d/waitAllMounts.conf' changed from 0666 (rw-rw-rw-) to 0644 (rw-r--r--)
Reload systemd daemon ...
Get:1 file:/var/cache/openmediavault/archives InRelease
Ign:1 file:/var/cache/openmediavault/archives InRelease
Get:2 file:/var/cache/openmediavault/archives Release
Ign:2 file:/var/cache/openmediavault/archives Release
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Ign:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Get:3 file:/var/cache/openmediavault/archives Packages
Get:4 file:/var/cache/openmediavault/archives Contents (deb)
Ign:4 file:/var/cache/openmediavault/archives Contents (deb)
Get:5 file:/var/cache/openmediavault/archives Contents (deb)
Ign:5 file:/var/cache/openmediavault/archives Contents (deb)
Hit:6 http://deb.debian.org/debian bullseye InRelease
Hit:7 http://deb.debian.org/debian bullseye-updates InRelease
Get:8 http://security.debian.org/ bullseye-security InRelease [48.4 kB]
Hit:9 http://packages.openmediavault.org/public shaitan InRelease
Hit:10 https://download.docker.com/linux/debian bullseye InRelease
Hit:11 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease
Hit:13 https://openmediavault.github.io/packages shaitan InRelease
Hit:12 http://mirrors.tuna.tsinghua.edu.cn/armbian bullseye InRelease
Get:14 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Hit:15 http://httpredir.debian.org/debian bullseye-backports InRelease
Fetched 96.7 kB in 7s (13.3 kB/s)
Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

The following additional packages will be installed:
containerd.io docker-ce-cli
Suggested packages:
cgroupfs-mount | cgroup-lite
Recommended packages:
apparmor docker-ce-rootless-extras libltdl7 pigz docker-buildx-plugin
The following NEW packages will be installed:
containerd.io docker-ce docker-ce-cli docker-compose-plugin
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 55.4 MB of archives.
After this operation, 235 MB of additional disk space will be used.
Get:1 https://download.docker.com/linux/debian bullseye/stable armhf containerd.io armhf 1.6.18-1 [20.7 MB]
Get:2 https://download.docker.com/linux/debian bullseye/stable armhf docker-ce-cli armhf 5:23.0.1-1debian.11bullseye [12.0 MB]
Get:3 https://download.docker.com/linux/debian bullseye/stable armhf docker-ce armhf 5:23.0.1-1debian.11bullseye [13.9 MB]
Get:4 https://download.docker.com/linux/debian bullseye/stable armhf docker-compose-plugin armhf 2.16.0-1debian.11bullseye [8738 kB]
Fetched 55.4 MB in 13s (4286 kB/s)
Selecting previously unselected package containerd.io.
(Reading database ...
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 48067 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.6.18-1_armhf.deb ...
Unpacking containerd.io (1.6.18-1) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a23.0.1-1debian.11bullseye_armhf.deb ...
Unpacking docker-ce-cli (5:23.0.1-1debian.11bullseye) ...
Selecting previously unselected package docker-ce.
Preparing to unpack .../docker-ce_5%3a23.0.1-1debian.11bullseye_armhf.deb ...
Unpacking docker-ce (5:23.0.1-1debian.11bullseye) ...
Selecting previously unselected package docker-compose-plugin.
Preparing to unpack .../docker-compose-plugin_2.16.0-1debian.11bullseye_armhf.deb ...
Unpacking docker-compose-plugin (2.16.0-1debian.11bullseye) ...
Setting up containerd.io (1.6.18-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up docker-compose-plugin (2.16.0-1debian.11bullseye) ...
Setting up docker-ce-cli (5:23.0.1-1debian.11bullseye) ...
Setting up docker-ce (5:23.0.1-1debian.11bullseye) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/docker.service.d
└─waitAllMounts.conf
Active: activating (auto-restart) (Result: exit-code) since Sun 2023-03-12 21:29:10 CST; 37ms ago
TriggeredBy: ● docker.socket
Docs: https://docs.docker.com/
Process: 15309 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
Main PID: 15309 (code=exited, status=1/FAILURE)
CPU: 836ms
dpkg: error processing package docker-ce (--configure):
installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
docker-ce
Failed to install docker.
Try fixing install...
Reading package lists...

Building dependency tree...

Reading state information...

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up docker-ce (5:23.0.1-1debian.11bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Drop-In: /etc/systemd/system/docker.service.d
└─waitAllMounts.conf
Active: activating (auto-restart) (Result: exit-code) since Sun 2023-03-12 21:30:04 CST; 39ms ago
TriggeredBy: ● docker.socket
Docs: https://docs.docker.com/
Process: 16637 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
Main PID: 16637 (code=exited, status=1/FAILURE)
CPU: 775ms
dpkg: error processing package docker-ce (--configure):
installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
docker-ce
Unable to fix docker install. in /usr/share/openmediavault/engined/rpc/omvextras.inc:296
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(619): OMVRpcServiceOmvExtras->{closure}('/tmp/bgstatusqA...', '/tmp/bgoutputNO...')
https://github.com/hzyitc/armbian-onecloud/issues/1 /usr/share/openmediavault/engined/rpc/omvextras.inc(298): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
https://github.com/hzyitc/armbian-onecloud/issues/2 [internal function]: OMVRpcServiceOmvExtras->doCommand(Array, Array)
https://github.com/hzyitc/armbian-onecloud/issues/3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
https://github.com/hzyitc/armbian-onecloud/issues/4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('doCommand', Array, Array)
https://github.com/hzyitc/armbian-onecloud/issues/5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('OmvExtras', 'doCommand', Array, Array, 1)
https://github.com/hzyitc/armbian-onecloud/pull/6 {main}

**Comment by chenychong** [comment]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-broken --fix-missing --auto-remove --allow-unauthenticated --show-upgraded --option DPkg::Options::="--force-confold" dist-upgrade 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

Calculating upgrade...

The following packages will be upgraded:
  openmediavault
Preconfiguring packages ...
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/2602 kB of archives.
After this operation, 13.3 kB of additional disk space will be used.
(Reading database ...
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 48298 files and directories currently installed.)
Preparing to unpack .../openmediavault_6.3.4-1_all.deb ...
Unpacking openmediavault (6.3.4-1) over (6.3.3-1) ...
Setting up openmediavault (6.3.4-1) ...
Creating configuration database ...
Migrating configuration database ...
  Running migration conf_6.3.3
INFO: The node 'routemetric' already exists at XPath '/config/system/network/interfaces/interface'.
INFO: The node 'routemetric6' already exists at XPath '/config/system/network/interfaces/interface'.
Setting up Salt environment ...
Processing system modifications ...
Setting up docker-ce (5:23.0.1-1~debian.11~bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/docker.service.d
             └─waitAllMounts.conf
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-03-13 20:23:10 CST; 40ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 3534 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 3534 (code=exited, status=1/FAILURE)
        CPU: 791ms
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for rsyslog (8.2102.0-2+deb11u1) ...
Processing triggers for openmediavault (6.3.4-1) ...
Restarting engine daemon ...
Updating workbench configuration files ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)


OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-broken --fix-missing --auto-remove --allow-unauthenticated --show-upgraded --option DPkg::Options::="--force-confold" dist-upgrade 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

Calculating upgrade...

The following packages will be upgraded:
  openmediavault
Preconfiguring packages ...
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/2602 kB of archives.
After this operation, 13.3 kB of additional disk space will be used.
(Reading database ...
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 48298 files and directories currently installed.)
Preparing to unpack .../openmediavault_6.3.4-1_all.deb ...
Unpacking openmediavault (6.3.4-1) over (6.3.3-1) ...
Setting up openmediavault (6.3.4-1) ...
Creating configuration database ...
Migrating configuration database ...
  Running migration conf_6.3.3
INFO: The node 'routemetric' already exists at XPath '/config/system/network/interfaces/interface'.
INFO: The node 'routemetric6' already exists at XPath '/config/system/network/interfaces/interface'.
Setting up Salt environment ...
Processing system modifications ...
Setting up docker-ce (5:23.0.1-1~debian.11~bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/docker.service.d
             └─waitAllMounts.conf
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-03-13 20:23:10 CST; 40ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 3534 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 3534 (code=exited, status=1/FAILURE)
        CPU: 791ms
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for rsyslog (8.2102.0-2+deb11u1) ...
Processing triggers for openmediavault (6.3.4-1) ...
Restarting engine daemon ...
Updating workbench configuration files ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
 in /usr/share/openmediavault/engined/rpc/apt.inc:225
Stack trace:
#0 /usr/share/php/openmediavault/rpc/serviceabstract.inc(619): Engined\Rpc\Apt->Engined\Rpc\{closure}('/tmp/bgstatusIa...', '/tmp/bgoutput5D...')
#1 /usr/share/openmediavault/engined/rpc/apt.inc(229): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#2 [internal function]: Engined\Rpc\Apt->upgrade(NULL, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('upgrade', NULL, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Apt', 'upgrade', NULL, Array, 1)
#6 {main}

**Comment by ihipop** [comment]
https://github.com/hzyitc/armbian-onecloud/issues/54#issuecomment-1257174989
