### ISSUE TITLE
插一张sd卡会影响进入系统嘛？

### ISSUE THREAD

**Issue by an429075824** [hzyitc/armbian-onecloud#104]
大佬 小白请教一下，如果插一张sd卡，如何正常进入系统并把产生的缓存啊 新安装的文件都存在sd卡上

**Comment by hzyitc** [comment]
你要是想完全使用SD卡启动的话，那直接把镜像文件刷入SD卡即可。

如果想使用eMMC启动，但部分东西放SD卡的话，自行查找下Linux的教程吧。
