### ISSUE TITLE
amlogic这个芯片的引脚定义在哪可以找到？

### ISSUE THREAD

**Issue by Zimengzhou** [hzyitc/armbian-onecloud#109]
现在能找到的数据手册中，没有写芯片引脚对应封装的哪个脚，我本想拆芯片重新画电路板的,引出上面没用到的脚。不过大佬既然已经研究出了玩客云上的引脚对应的硬件，就可以直接当arm开发板玩了

**Comment by hzyitc** [comment]
看`odroid-c1`的电路图

https://dn.odroid.com/S805/Schematics/odroid-c1+_rev0.4_20160226.pdf
