### ISSUE TITLE
请求打开CONFIG_DEBUG_INFO_BTF

### ISSUE THREAD

**Issue by k3bc999** [hzyitc/armbian-onecloud#110]
最近想尝试https://github.com/daeuniverse/dae
用此软件作为旁路由使用
但是其对内核有一定要求
![图片](https://user-images.githubusercontent.com/27000015/229326851-0778ce4c-f334-40cb-afe8-7919d7de70fe.png)
我之前对内核测试貌似是没有
CONFIG_DEBUG_INFO_BTF

使用dae给出的armbian内核则会造成无法启动
希望此内核选项可以打开

十分感谢

**Comment by hzyitc** [comment]
这直接开起了DEBUG了。作为默认选项发行不合适。

实在有需要的话自行编译吧。
