### ISSUE TITLE
现在的kernel路径在哪个目录

### ISSUE THREAD

**Issue by shao21104** [hzyitc/armbian-onecloud#112]
以前版本通常kernel路径在/usr/src/...里，现在的版本src里是空的kernel移动到哪里了？
![Uploading 1680624058666(1).png…]()
![Uploading 1680624113307(1).png…]()

**Comment by hzyitc** [comment]
你是说 headers 吗？

自行安装 `linux-headers-edge-meson` 或 `linux-headers-current-meson` 包
