### ISSUE TITLE
启动不成功,可以输用户名和密码,但是出现login incorrect

### ISSUE THREAD

**Issue by KayXin** [hzyitc/armbian-onecloud#113]
感谢大佬一直更新
不知道哪启动有问题,设备很久没有重启,前两天重启了一次,无法ssh,网口只有绿灯闪,黄灯不亮
连接显示器,键盘后,可以输入密码和用户名,但是一直提示login incorrect,确定密码没有问题
这段时间可能有的变化,就是我把路由器ipv6给关掉了,不知道这个会影响设备启动么?

查资料说可能是文件权限有变化,但是无法进入他们说的单用户模式,我这也操作不了

**Comment by hzyitc** [comment]
这大概率是个例。

可以试试看从U盘启动后去修复原系统。实在不行就重刷机吧。

**Comment by KayXin** [comment]
尝试了很多,没办法,最后还是又刷了一次

网口的问题,大概是灯坏了,现在正常也就一个灯亮

**Comment by hzyitc** [comment]
网口灯就是一个，我没修复这个问题。
