### ISSUE TITLE
系统启动很慢

### ISSUE THREAD

**Issue by qwasddd** [hzyitc/armbian-onecloud#116]
从最新的Armbian_23.05.0-trunk_Onecloud_bullseye_current_6.1.22.burn 和6.21的也试过都会很慢，现在换成Armbian_23.02.0-trunk_Onecloud_bullseye_current_5.15.91_minimal.burn 就快一点吧，不过也是启动了很久都进不去系统[https://i.postimg.cc/1tvr42j8/Screenshot-2023-04-09-21-30-09.png](url)
[https://i.postimg.cc/kMhyCrSZ/Screenshot-2023-04-09-21-35-58.png](url)
[https://i.postimg.cc/QCPgJ5ss/Screenshot-2023-04-09-22-45-59.png](url)

**Comment by ihipop** [comment]
我看到第二张图有什么东西崩溃了

你插USB外设了吗？拔掉试试？

**Comment by qwasddd** [comment]
> 我看到第二张图有什么东西崩溃了
> 
> 你插USB外设了吗？
只插HDMI线都一样，好几个版本都不行，启动很慢。现在换了Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.9.burn这个版本，启动快很多了。七八分钟内就能启动完，就是有时候网卡起不来，down状态

**Comment by hzyitc** [comment]
![image](https://user-images.githubusercontent.com/25414097/232747691-7ca1bb16-f52d-4799-9762-e1c9d4dd30bf.png)

看这条信息上面的内容。

网卡问题见 #75
