### ISSUE TITLE
什么时候更新u-boot

### ISSUE THREAD

**Issue by Potterli20** [hzyitc/armbian-onecloud#118]
什么时候更新u-boot

**Comment by Potterli20** [comment]
官方更新了很多，改得多

**Comment by hzyitc** [comment]
难度有点大。主线u-boot完全不支持meson-mx，之后可能可以尝试移植，但我最近太忙了。

**Comment by hzyitc** [comment]
以及目前这个版本的u-boot也够用了，除了不支持ext4以外没啥大问题。

**Comment by Potterli20** [comment]
> 以及目前这个版本的u-boot也够用了，除了不支持ext4以外没啥大问题。

因为我想知道最新的uboot和现在的版本有什么区别，我想体验一下最新的uboot的问题😂

**Comment by hzyitc** [comment]
目前用的版本在这

https://github.com/hzyitc/u-boot-onecloud

基于[uboot-meson-next-2015-04-01](https://github.com/hzyitc/u-boot-onecloud/tree/uboot-meson-next-2015-04-01)，源头是u-boot [v2011.03](https://github.com/hzyitc/u-boot-onecloud/tree/v2011.03)。

**Comment by Potterli20** [comment]
> 目前用的版本在这
> 
> https://github.com/hzyitc/u-boot-onecloud
> 
> 基于[uboot-meson-next-2015-04-01](https://github.com/hzyitc/u-boot-onecloud/tree/uboot-meson-next-2015-04-01)，源头是u-boot [v2011.03](https://github.com/hzyitc/u-boot-onecloud/tree/v2011.03)。

这个我是知道的
