### ISSUE TITLE
这个玩客云的固件，盒子能刷吗？hg680lc cpu：s905l3 

### ISSUE THREAD

**Issue by xxx854** [hzyitc/armbian-onecloud#119]
![屏幕截图 2023-04-17 134644](https://user-images.githubusercontent.com/77531464/232409935-ae187155-63ef-4dd2-959c-06af0970400d.png)

**Comment by hzyitc** [comment]
本仓库仅支持s805，s905的话armbian官方确实支持，但不是本人负责。
