### ISSUE TITLE
/etc/apt/sources.list.d box86.list nala.list 这两个源是干嘛的？ 可以删除吗？

### ISSUE THREAD

**Issue by fvlw** [hzyitc/armbian-onecloud#12]
更新的时候提示拉取出错
![图片](https://user-images.githubusercontent.com/71577616/173597834-58d7296b-21be-4b42-8ffb-fbec74947f21.png)

**Comment by hzyitc** [comment]
`armbian` 官方添加的

[https://github.com/ptitSeb/box86](https://github.com/ptitSeb/box86)

[https://gitlab.com/volian/nala](https://gitlab.com/volian/nala)
