### ISSUE TITLE
CPU频率不能自定义调整了bullseye_edge_6.2.10(已解决)

### ISSUE THREAD

**Issue by shao21104** [hzyitc/armbian-onecloud#120]
今天试了Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.10，发现 armbian-config里 CPU频率不能自定义调整了，设置任何选项保存后再进去看都回到默认值

**Comment by DenneyTang** [comment]
今天刚好碰到 一样问题，修改一下这个文件/etc/default/cpufrequtils ：

> ENABLE=true
> MIN_SPEED=1536000
> MAX_SPEED=1536000
> GOVERNOR=performance

之后重启服务 service cpufrequtils restart

**Comment by shao21104** [comment]
nano /etc/default/cpufrequtils 进去后修改性能模式后USB插拔，网络断续，卡顿等一系列莫名其妙毛病都解决了
![1682259892895](https://user-images.githubusercontent.com/126444630/233845866-24806692-d267-446c-95be-1d1924ac3bbf.jpg)

**Comment by shao21104** [comment]
USB无线网卡连接正常
![USB无线](https://user-images.githubusercontent.com/126444630/233847800-e54d3997-c33d-4fda-9aca-69923cb280cf.jpg)

**Comment by pawellii** [comment]
> nano /etc/default/cpufrequtils 进去后修改性能模式后USB插拔，网络断续，卡顿等一系列莫名其妙毛病都解决了 ![1682259892895](https://user-images.githubusercontent.com/126444630/233845866-24806692-d267-446c-95be-1d1924ac3bbf.jpg)

长期保持高性能模式不会出问题吗？发热啥的正常吗？

**Comment by hzyitc** [comment]
https://github.com/hzyitc/armbian-onecloud/issues/87#issuecomment-1487475766
