### ISSUE TITLE
关于挂载移动硬盘后开机启动项问题

### ISSUE THREAD

**Issue by pawellii** [hzyitc/armbian-onecloud#125]
刷了最新版的直刷包到eMMc
Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.12.burn.img
我想实现开机自动挂载移动硬盘，但是移动硬盘不管插到哪个usb口开机都会卡在u-boot界面，如下图
![222](https://user-images.githubusercontent.com/35719095/234453895-99d0ec12-a47c-45ce-9e4b-8e8edd37d0fc.jpg)
我的移动硬盘是用fdisk分了一个区，然后分区格式化为ext4的，里面也没有系统或者引导啥的，就是空的
然后我怀疑是引导顺序问题，尝试了各种方法去修改，均未成功，可能我方法没找对

最后偶然发现当靠近hdmi接口的那个usb口插上普通U盘（ntfs的，无系统或者引导）或者无线键鼠的接收器或者其他的类似usb设备之后，再把移动硬盘插到另一个usb口上以后，就可以正常从eMMc启动。如下图，会提示Try to boot from USB...Fail，然后就可以正常从eMMc启动了。
![111](https://user-images.githubusercontent.com/35719095/234454758-3cc78eb6-0ddf-4ddd-946d-c7fb48924cb2.jpg)
虽然问题解决了，但是还是想问一下大佬具体原因是啥？怎么才能实现只插移动硬盘然后正常启动呢？

**Comment by hzyitc** [comment]
https://github.com/hzyitc/u-boot-onecloud/issues/6
