### ISSUE TITLE
关于更新bullseye_edge_6.3.1后经常死机。

### ISSUE THREAD

**Issue by wgf520** [hzyitc/armbian-onecloud#127]
Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.3.1.img.xz
更新后重新启动，前面几分钟正常运行，过段时间就死机，SSH无法连接，拔电源重启同样问题，运行一段时间就死机了（有时 时间坚持久点才会死机）
奔溃日志不知道在哪里查看

**Comment by lanlanpy** [comment]
测试armbian挂机后台抓取内核异常信息命令，后面带& cat /proc/kmsg >/root/kernel.txt & 执行后挂机就行，如果ssh连不上了 重启后把在root目录下的kernel.txt上传，系统日志在/var/log里面，有好几个都可以上传

**Comment by lanlanpy** [comment]
你的主板是什么版本的
