### ISSUE TITLE
关于主板v1.3增加sdio 板载wifi RTL8189ETV支持

### ISSUE THREAD

**Issue by lanlanpy** [hzyitc/armbian-onecloud#129]
玩客云群友 二少 测试在英菲克安卓固件正常使用

内核日志关于wifi的关键信息
<4>[    2.170599@0] wifi_dev_probe
<4>[    2.173298@0] wifi_dt : interrupt_pin=GPIOX_21
<4>[    2.177746@0] wifi_dt : irq_num=null
<4>[    2.181277@0] wifi_dt : irq_trigger_type=GPIO_IRQ_HIGH
<4>[    2.186369@0] wifi_dt : power_on_pin=GPIOX_11
<4>[    2.190721@0] wifi_dt : power_on_pin2=GPIOX_11
<4>[    2.195123@0] interrupt_pin=118, irq_num=4, irq_trigger_type=0, power_on_pin=108,clock_32k_pin=107

<4>[    4.837819@3] wifi_request_32k_clk : OFF-->ON for bt_rfkill
<4>[    4.837867@3] clock_32k_pin(107) : (null)
<4>[    4.841753@3] clock_32k_pin(107) : sdio_wifi

附上内核日志，包含连上wifi ap的过程。。
[安卓驱动成功8189etv芯片wifi的ttl日志.log](https://github.com/hzyitc/armbian-onecloud/files/11581643/8189etv.wifi.ttl.log)

芯片购买，非推销！！！【淘宝】https://m.tb.cn/h.UEvujqT?tk=DEZMdLRefwI CZ0001 「RTL8189ETV 3.3V SDIO接口 2.4G低功耗模组 WIFI无线模块全新现货」
点击链接直接打开 或者 淘宝搜索直接打开

成功案例
【玩客云 1.3版本加装wifi 模块-哔哩哔哩】 https://b23.tv/gDRJf2e

电路补全图，来自上面的B站UP主
![电路补全图](https://github.com/hzyitc/armbian-onecloud/assets/20089317/d16d7db1-6eb1-4adb-990e-fa451640ef3f)

驱动成功的dts  

[wky-wifi.dts.txt](https://github.com/hzyitc/armbian-onecloud/files/11581648/wky-wifi.dts.txt)

希望大佬有空可以对主线内核的dts 添加sdio wifi的支持 ，再次感谢大佬的辛劳付出。

**Comment by hzyitc** [comment]
#29 不重复开issue。
