### ISSUE TITLE
玩客云刷机保姆式教程，简单直接的写给你

### ISSUE THREAD

**Issue by indiboy** [hzyitc/armbian-onecloud#13]
=========================
下载镜像文件写入U盘，下载解压下面文件后
https://github.com/hzyitc/armbian-onecloud/files/8876513/s805_autoscript.zip
复制到BOOT分区就可以了。插上U盘到靠近网线的U口通电就好了。
=========================
我使用的不是精简底包，是powersee提供的底包，精简底包也应该没问题，那个能刷上去用哪个。
资源地址如下。https://pan.powersee.top/%E5%85%B1%E4%BA%AB%E6%96%87%E4%BB%B6%E5%A4%B9/%E7%8E%A9%E5%AE%A2%E4%BA%91/s805_flash_snail.img.xz
https://pan.powersee.top/
 http://veger.ys168.com/
===========================
刷机工具：
https://androidmtk.com/download-amlogic-usb-burning-tool
j镜像写入工具：
https://www.alexpage.de/usb-image-tool/download/
===============================
建议不要先拆机，直接插双公头usb数据线即可
或者按住重置键开机，发现硬件即可刷机，如果出错
1.多试几次 2.换个USB口 3.重启机器 4.换个机器
===============================
短接刷机方法，请自行百度，需要拆机短接，版本不一样短接不一样，其余的一致。
===============================

**Comment by indiboy** [comment]
知道了，下载镜像文件写入U盘，下载解压下面文件后
https://github.com/hzyitc/armbian-onecloud/files/8876513/s805_autoscript.zip
复制到BOOT分区就可以了。插上U盘到靠近网线的U口通电就好了。

**Comment by indiboy** [comment]
写入EMMC使用一下脚本。
https://github.com/raysworld/onecloud-emmc-install
下载后解压到BOOT盘install下面
cd /boot/install
运行 ./install.sh 即可
-------------------------
我不知道是不是我的U盘问题，镜像写入U盘后是只读的。
而写入EMMC后是正常的。

**Comment by lbbboy** [comment]
> ## 写入EMMC使用一下脚本。
> https://github.com/raysworld/onecloud-emmc-install
> 下载后解压到BOOT盘install下面
> cd /boot/install
> 运行 ./install.sh 即可
> ## **我不知道是不是我的U盘问题，镜像写入U盘后是只读的。 而写入EMMC后是正常的。**
> 确认U盘问题，给后来者一个提醒

有问题，我 1.0 的用这个写入emmc  灯都不亮了。

**Comment by indiboy** [comment]
应该没问题，我的也是1.0，写入后启动时候是蓝色，启动后是红色。

**Comment by lbbboy** [comment]
> 应该没问题，我的也是1.0，写入后启动时候是蓝色，启动后是红色。

重新搞了下写入了，CPU 频率读不到，EMMC P1 目录没有挂载。

**Comment by qwasddd** [comment]
请问你的7月后面的版本也能用这个方法刷进去吗

**Comment by indiboy** [comment]
> 

应该时一样的。

**Comment by qwasddd** [comment]
> > 
> 
> 应该时一样的。

我的进不了系统，7月前的就可以成功，怪了

**Comment by jacelift** [comment]
> 写入U盘后是只读的

其实这是U盘从usb口启动导致的问题，在ssh里，输入命令：`mount -o remount,rw /`回车即可，或者重启试试。
