### ISSUE TITLE
error -ENODEV: _opp_set_regulators: no regulator (mali) found

### ISSUE THREAD

**Issue by hkbase** [hzyitc/armbian-onecloud#133]
root@onecloud:~# dmesg |grep gpu
[    3.286702] lima d00c0000.gpu: gp - mali450 version major 0 minor 0
[    3.289292] lima d00c0000.gpu: pp0 - mali450 version major 0 minor 0
[    3.295555] lima d00c0000.gpu: pp1 - mali450 version major 0 minor 0
[    3.301865] lima d00c0000.gpu: l2 cache 8K, 4-way, 64byte cache line, 128bit external bus
[    3.309968] lima d00c0000.gpu: l2 cache 64K, 4-way, 64byte cache line, 128bit external bus
[    3.319057] lima d00c0000.gpu: bus rate = 159375000
[    3.323052] lima d00c0000.gpu: mod rate = 24000000
**[    3.327922] lima d00c0000.gpu: error -ENODEV: _opp_set_regulators: no regulator (mali) found**
[    3.337890] [drm] Initialized lima 1.1.0 20191231 for d00c0000.gpu on minor 0

**Comment by hkbase** [comment]
如果在执行 `zcat /proc/config.gz | grep CONFIG_REGULATOR | grep CONFIG_LIMA` 命令时，没有找到 `CONFIG_LIMA`，那么说明您的内核可能没有启用Lima GPU的驱动程序。

要在内核中启用Lima GPU的支持，请按照以下步骤进行操作：

1. 打开内核配置界面。您可以使用以下命令打开内核配置界面：

   ````
   make menuconfig
   ```

2. 在内核配置界面中找到 `Device Drivers` 菜单，并进入该菜单。

3. 在 `Device Drivers` 菜单中，找到 `Graphics support` 选项，并进入该选项。

4. 在 `Graphics support` 选项中，找到 `ARM Mali Midgard and Bifrost support` 选项，并启用它。

5. 保存内核配置并退出。

6. 重新编译内核并安装新的内核。您可以使用以下命令重新编译内核：

   ````
   make -j8 && make modules_install && make install
   ```

7. 重启设备并检查 `CONFIG_LIMA` 是否已启用。您可以使用以下命令检查：

   ````
   zcat /proc/config.gz | grep CONFIG_REGULATOR | grep CONFIG_LIMA
   ```

如果您按照以上步骤进行操作，应该能够在内核中启用Lima GPU的支持，并解决 `-ENODEV: _opp_set_regulators: no regulator (mali) found` 错误。

**Comment by hkbase** [comment]
以上修复操作，是chatgpt给出的答案，仅供@hzyitc参考。

**Comment by hzyitc** [comment]
chatgpt说的是错的。

就是`dts`里面没配置mali的supply。故意不配置的，因为cpu和gpu用同一个supply，所以两边同时配置的话会冲突。
