### ISSUE TITLE
armbian-config配置里的ISPconfig安装不上

### ISSUE THREAD

**Issue by chocoalwayslate** [hzyitc/armbian-onecloud#134]
armbian-config配置里的ISPconfig安装不上，卡在getmail4的地方。更换多个源也无法解决，似乎armbian-config不是用的系统的源，系统源里面也下载不到getmail4，也没有找到安装脚本存储的位置。
code主可以指导以下吗。

**Comment by hzyitc** [comment]
我个人不用`armbian-config`，你看看报啥错误。要不去官方提issue。

**Comment by chocoalwayslate** [comment]
嗯呢 谢谢，armbian-config原来是单独开源程序……
