### ISSUE TITLE
烧录总是出错

### ISSUE THREAD

**Issue by ChenKe404** [hzyitc/armbian-onecloud#135]
系统：win10
烧录工具版本：2.1.6.8
固件：edge/current 6.1.32 minimal burn
玩客云：老版S805主板(短接点在主板背面那个)
操作：短接后插电识别到usb后立即松开短接并点击开始。
结果：burn固件总是在1%报错；minimal burn有机会超过90%但总在97%停顿约一分钟后报错。
1%时提示：[0x10102002]Romcode/初始化DDR/初始化寄存器/USB控制命令出错
97%时提示：[0x30405004]UBOOT/烧录分区 rootfs/检验分区/命令结果返回错误

大佬们可否指点一二，电脑上的usb口都试了一个遍了，双头线也换了两三根来用，结果都是一样。

**Comment by hzyitc** [comment]
校验出错不是超时？

校验失败直接重启应该也能启动。

估计是emmc有坏块。你可以装到SD卡。

**Comment by ChenKe404** [comment]
那如何从sd卡引导系统呢，我刷到sd卡，它还是启动原来的系统。我尝试刷您u-boot-onecloud仓库里的eMMC.burn.img，结果也是总是在%1报错，刷不进去。

**Comment by ChenKe404** [comment]
![IMG_0158](https://github.com/hzyitc/armbian-onecloud/assets/75658944/9660429a-bc3e-4ef7-84b5-002a779525b6)
eMMC.burn.img刚刚莫名其妙刷进去了，现在卡在这

**Comment by ChenKe404** [comment]
是要用ttl执行仓库主页给的命令吗？

**Comment by ChenKe404** [comment]
原来是我刷完eMMc.burn.img没拔usb线，没读到SD卡>_<。拔了重启就进去了。
