### ISSUE TITLE
请问这个能用来刷赚钱宝2代吗？那个机子也是晶晨S805的方案

### ISSUE THREAD

**Issue by r81892489** [hzyitc/armbian-onecloud#139]
如题，不是很懂系统底层，跟着教程把玩客云刷入armbian，然后各种折腾wrt,OS,docker,简直太快乐了，学到很多东西，手里还有一台闲置的赚钱宝2代，不知道能不能直接用这个刷机

**Comment by hzyitc** [comment]
得修改，我记得好像有别人做这个板子，你找找吧。
