### ISSUE TITLE
挂载移动硬盘后，能打开移动硬盘里的一级文件夹，下一级的文件及文件夹没有

### ISSUE THREAD

**Issue by mzautumn** [hzyitc/armbian-onecloud#140]
挂载移动硬盘后，能打开移动硬盘里的一级文件夹，下一级的文件及文件夹没有，不显示。

**Comment by mzautumn** [comment]
挂载方法是用mount挂载，并在/etc/fstab内添加UUID，最后mount -a保存并重启。
之前刷其他版本的系统一直用的这个方法，没问题。

**Comment by mzautumn** [comment]
是不支持NTFS 格式吗？

**Comment by hzyitc** [comment]
emmm，大概率是操作问题吧。

文件系统部分完全跟上游是一样的，如果有问题应该有别人向内核反应了。
