### ISSUE TITLE
大佬有计划适配openwrt吗？玩客云当旁路由挺不错

### ISSUE THREAD

**Issue by shiyu1314** [hzyitc/armbian-onecloud#141]

**Comment by Potterli20** [comment]
op不是有？还用适配？l大的源

**Comment by shiyu1314** [comment]
> op不是有？还用适配？l大的源

那个只支持u盘和SD卡不支持emmc

**Comment by hzyitc** [comment]
把patch加进去就行，我就懒得维护了。

https://github.com/armbian/build/blob/main/patch/kernel/archive/meson-6.1/generic-Revert-mmc-core-Set-HS-clock-speed-before-sending-HS-CMD13.patch

**Comment by Potterli20** [comment]
> 把patch加进去就行，我就懒得维护了。
> 
> https://github.com/armbian/build/blob/main/patch/kernel/archive/meson-6.1/generic-Revert-mmc-core-Set-HS-clock-speed-before-sending-HS-CMD13.patch

网卡修不了？你置顶我的帖子那个

**Comment by ahhfzwl** [comment]
这个建议不错，支持，现有的玩客云openwrt固件都有缺陷；要么是3.1内核，很多插件不支持；要么只能U盘启动，刷不进EMMC。市场上就没有一个完美的。

**Comment by U201413497** [comment]
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8299703&highlight=%E7%8E%A9%E5%AE%A2%E4%BA%91

这个我刷进去很完美。

**Comment by shiyu1314** [comment]
https://github.com/coolsnowwolf/lede/pull/11453
