### ISSUE TITLE
armbian-software命令用不了

### ISSUE THREAD

**Issue by fsea** [hzyitc/armbian-onecloud#142]
![image](https://github.com/hzyitc/armbian-onecloud/assets/7764467/7c7d6938-a5f0-4d5f-964f-85f0b00d979c)

**Comment by hzyitc** [comment]
如果我没记错的话armbian就没这命令啊。你哪里看到的?

**Comment by d0ngpeng** [comment]
N1有

**Comment by hzyitc** [comment]
可能是第三方加的，armbian官方那边印象中是没看到。

**Comment by gbm777** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian   这个版本有这个一系列命令

但是似乎只支持玩客云pro。
