### ISSUE TITLE
Armbian_23.08.0-trunk_Onecloud_bullseye_edge_6.3.6_minimal版本网卡流量统计问题

### ISSUE THREAD

**Issue by Carlos6668** [hzyitc/armbian-onecloud#143]
下载累计流量超过4GB后就会清零然后重新开始，一直反复，是否可以检查一下是什么问题，谢谢。

**Comment by hzyitc** [comment]
#93

不过我自己无法复现，请提供具体信息。

**Comment by Carlos6668** [comment]
https://github.com/hzyitc/armbian-onecloud/assets/16048692/87a328c5-88ae-4240-97a8-6b7494f3d6b3
