### ISSUE TITLE
玩客云s805编译问题咨询

### ISSUE THREAD

**Issue by popoupou** [hzyitc/armbian-onecloud#146]
请问大佬，我用官方库编译，怎样才能编译出可以线刷的包呢？我魔改了内存到2g，刷大佬编好的包只能识别1g，我看dtb文件里内存那里好像是设置的1g，所以想自己修改一下重新编译一个固件，就是不知道该怎么搞，目前编出来的固件用burning_tool导入直接就报错了，希望大佬指点下，感谢

**Comment by popoupou** [comment]
用大佬库里的action已经编译了固件了，改了dts里面memory里面的内存大小，结果刷了以后还是只能识别1g，不知道还要改哪些地方了，还是说这个板子没法改内存呢？

**Comment by hzyitc** [comment]
内存初始化在uboot。

以及有不少板子的dts里面的memory配置会被uboot修改，这板子我忘了会不会了。
