### ISSUE TITLE
最新版的armbian支持哪些usb无线网卡?

### ISSUE THREAD

**Issue by biluokong** [hzyitc/armbian-onecloud#147]

**Comment by Androgynus** [comment]
我猜你可能希望不用自己编译驱动就能直接用，可以参考一下这个
https://github.com/morrownr/USB-WiFi
底下这个网站可以查到一些USB无线网卡的芯片以及内核支持情况
https://deviwiki.com/wiki/Main_Page

**Comment by hzyitc** [comment]
主线kernel支持的+armbian支持的
