### ISSUE TITLE
能提供一些安装无线网卡的资料吗？

### ISSUE THREAD

**Issue by zzw668** [hzyitc/armbian-onecloud#157]
能提供一些安装无线网卡的资料吗？有些无线网卡不能被识别，比如RTL8188EUS
/rtl8188eu# make all
make ARCH=arm CROSS_COMPILE= -C /lib/modules/6.1.50-current-meson/build M=/root/rtl8188eu  modules
make[1]: *** /lib/modules/6.1.50-current-meson/build: No such file or directory.  Stop.
make: *** [Makefile:155: modules] Error 2

make是一直出错不知道怎么弄？

**Comment by hzyitc** [comment]
kernel和armbian支持的网卡都可以用。
