### ISSUE TITLE
Incorrent VCC_CORE cause boots fail or work unstably

### ISSUE THREAD

**Issue by hzyitc** [hzyitc/armbian-onecloud#16]
The board use `PWM_D` to adjust `VCC_CORE`. But we don't driver it.

板子使用 `PWM_D` 来调节 `VCC_CORE`。 但我们没有驱动它。

Fixed in [branch fix-vcc_core-temportally](https://github.com/hzyitc/armbian-onecloud/tree/fix-vcc_core-temportally) temportally.

在 [fix-vcc_core-temportally分支](https://github.com/hzyitc/armbian-onecloud/tree/fix-vcc_core-temportally) 临时修复.

~~In `V1.3 board` `vcc_core` is 1.1V, but in `V1.0 board` it's 1.0V. So `CPU` doesn't work well in 1.5GHz and the boot fails.~~

~~在 `V1.3板子` 上 `vcc_core` 是 1.1V，但在 `V1.0板子` 上 `vcc_core` 是 1.0V。所以 `CPU` 在 1.5GHz 时工作不稳定，故导致启动失败。~~

**Comment by MDCY9008** [comment]
我使用了最新提交的代码编译测试了一下，```1.0板子```启动及cpu一切正常，频率最高1.32Ghz，调频正常。
但是我看patch的描述，如果是```1.3```的板子需要修改patch内电压重新编译吗？

**Comment by hzyitc** [comment]
> 我使用了最新提交的代码编译测试了一下，`1.0板子`启动及cpu一切正常，频率最高1.32Ghz，调频正常。 但是我看patch的描述，如果是`1.3`的板子需要修改patch内电压重新编译吗？

可以不用，那只是描述性的内容

**Comment by hzyitc** [comment]
目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏

**Comment by MDCY9008** [comment]
> 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏

我从官方2.5.1的系统包提取了DTB，不知道有没有帮助
https://musetransfer.com/s/v0kgwkezo

**Comment by hzyitc** [comment]
> > 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏
> 
> 我从官方2.5.1的系统包提取了DTB，不知道有没有帮助 https://musetransfer.com/s/v0kgwkezo

他还真有`PWM`控制`SoC`电压。

不过跟他`dts`描述的不一致，使用的是`PWM_D`而不是`PWM_C`。

待研究。

**Comment by MDCY9008** [comment]
> > > 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏
> > 
> > 
> > 我从官方2.5.1的系统包提取了DTB，不知道有没有帮助 https://musetransfer.com/s/v0kgwkezo
> 
> 他还真有`PWM`控制`SoC`电压。
> 
> 不过跟他`dts`描述的不一致，使用的是`PWM_D`而不是`PWM_C`。
> 
> 待研究。

测试了下新发布的临时修复，CPU又不显示频率了，但是还是可以启动的。板子是```1.0```的

**Comment by hzyitc** [comment]
> > > > 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏
> > > 
> > > 
> > > 我从官方2.5.1的系统包提取了DTB，不知道有没有帮助 https://musetransfer.com/s/v0kgwkezo
> > 
> > 
> > 他还真有`PWM`控制`SoC`电压。
> > 不过跟他`dts`描述的不一致，使用的是`PWM_D`而不是`PWM_C`。
> > 待研究。
> 
> 测试了下新发布的临时修复，CPU又不显示频率了，但是还是可以启动的。板子是`1.0`的

无法复现。

你用的是哪个`分支`？

**Comment by MDCY9008** [comment]
> 

debian11 edge minimal

**Comment by MDCY9008** [comment]
> > > > > 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏
> > > > 
> > > > 
> > > > 我从官方2.5.1的系统包提取了DTB，不知道有没有帮助 https://musetransfer.com/s/v0kgwkezo
> > > 
> > > 
> > > 他还真有`PWM`控制`SoC`电压。
> > > 不过跟他`dts`描述的不一致，使用的是`PWM_D`而不是`PWM_C`。
> > > 待研究。
> > 
> > 
> > 测试了下新发布的临时修复，CPU又不显示频率了，但是还是可以启动的。板子是`1.0`的
> 
> 无法复现。
> 
> 你用的是哪个`分支`？

debian11 edge minimal

**Comment by hzyitc** [comment]
> > > > > > 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏
> > > > > 
> > > > > 
> > > > > 我从官方2.5.1的系统包提取了DTB，不知道有没有帮助 https://musetransfer.com/s/v0kgwkezo
> > > > 
> > > > 
> > > > 他还真有`PWM`控制`SoC`电压。
> > > > 不过跟他`dts`描述的不一致，使用的是`PWM_D`而不是`PWM_C`。
> > > > 待研究。
> > > 
> > > 
> > > 测试了下新发布的临时修复，CPU又不显示频率了，但是还是可以启动的。板子是`1.0`的
> > 
> > 
> > 无法复现。
> > 你用的是哪个`分支`？
> 
> debian11 edge minimal

贴下`dmesg`日志吧

**Comment by MDCY9008** [comment]
> > > > > > > 目前最大的问题是，我并没有一个有效的方法来识别板子型号。`V1.3的板子`是可以跑到 1.5GHz 的，都限制在 1.3GHz 的话，性能上吃点亏
> > > > > > 
> > > > > > 
> > > > > > 我从官方2.5.1的系统包提取了DTB，不知道有没有帮助 https://musetransfer.com/s/v0kgwkezo
> > > > > 
> > > > > 
> > > > > 他还真有`PWM`控制`SoC`电压。
> > > > > 不过跟他`dts`描述的不一致，使用的是`PWM_D`而不是`PWM_C`。
> > > > > 待研究。
> > > > 
> > > > 
> > > > 测试了下新发布的临时修复，CPU又不显示频率了，但是还是可以启动的。板子是`1.0`的
> > > 
> > > 
> > > 无法复现。
> > > 你用的是哪个`分支`？
> > 
> > 
> > debian11 edge minimal
> 
> 贴下`dmesg`日志吧

https://musetransfer.com/s/r5ho33bsd（有效期至7月28日）

**Comment by hzyitc** [comment]
可能是由于`regulator`被编译成了`module`，导致加载不到，已修复

**Comment by hzyitc** [comment]
> 测试了一下，结果还是安装不了omv6，这次重启后还能进入系统，但是依旧编译不成功。

omv问题我这边无法复现，在没有相关日志的情况下，我也没法排查原因

**Comment by hzyitc** [comment]
> 可能是由于`regulator`被编译成了`module`，导致加载不到，已修复

由于`ci脚本`的问题，`releases`中**第二个**才是最新编译结果

**Comment by MDCY9008** [comment]
> 可能是由于`regulator`被编译成了`module`，导致加载不到，已修复

还是一样的结果，issue#1一样的现象。

**Comment by hzyitc** [comment]
那就只能等有空的时候分析下源码了。

如果确实需要调频，可以把`dts`中的`cpu-supply = <&vcc_core>;`注释掉

**Comment by MDCY9008** [comment]
> 那就只能等有空的时候分析下源码了。
> 
> 如果确实需要调频，可以把`dts`中的`cpu-supply = <&vcc_core>;`注释掉

会不会是vin-supply的问题

**Comment by MDCY9008** [comment]
![image](https://user-images.githubusercontent.com/54255527/176797555-0811193c-09a0-4be6-bcb1-9464487f67d9.png)
CPU调频正常，正常启动，```1.0```的板子，感觉电压有点奇怪，最小值是0.748V吗

**Comment by hzyitc** [comment]
Fix in [b4b4546](https://github.com/hzyitc/armbian-onecloud/commit/b4b4546a1830b3241ca4b95d8a708c114cb2ca8c)
