### ISSUE TITLE
第一次使用直刷包，需要勾选 “擦除flash" 和  ”擦除bootloader" 吗 ？

### ISSUE THREAD

**Issue by trump-7575** [hzyitc/armbian-onecloud#160]
刚买了一台 网心云 （ 和玩客云是一样的 ？ ） ， 第一次刷机，想直接使用 最新的直刷包直接线刷，请问是不是要 勾选 “擦除flash" 和  ”擦除bootloader" 啊 ？

**Comment by wp5970** [comment]
默认勾选，不用修改

**Comment by hzyitc** [comment]
保存默认即可。
