### ISSUE TITLE
rtl8821CU网卡，上电启动卡住内核

### ISSUE THREAD

**Issue by wellexp** [hzyitc/armbian-onecloud#164]
rtl8821CU驱动地址：https://github.com/brektrou/rtl8821CU
驱动安装后，按readme中的方案安装并添加udev规则。系统起来后插上网卡使用正常。但插着网卡上电会卡住。

启动过程中发现usb设备后，反复reset usb

[    4.879743] usb 1-1: new high-speed USB device number 2 using dwc2
[    5.131537] usb-storage 1-1:1.0: USB Mass Storage device detected
[    5.133409] scsi host0: usb-storage 1-1:1.0
[    6.172870] scsi 0:0:0:0: CD-ROM            Realtek  Driver Storage   1.00 PQ: 0 ANSI: 0 CCS
[    6.184493] sr 0:0:0:0: [sr0] scsi-1 drive
[    6.184576] cdrom: Uniform CD-ROM driver Revision: 3.20
[    6.193427] sr 0:0:0:0: Attached scsi CD-ROM sr0
[    6.799809] usb 1-1: reset high-speed USB device number 2 using dwc2---------内核复位USB设备,会一直复位下去
[   15.210373] platform iio-hwmon: deferred probe pending
[   15.210450] platform cpufreq-dt: deferred probe pending
[   37.889822] usb 1-1: reset high-speed USB device number 2 using dwc2
[   68.609810] usb 1-1: reset high-speed USB device number 2 using dwc2
[   99.329817] usb 1-1: reset high-speed USB device number 2 using dwc2
[  130.049800] usb 1-1: reset high-speed USB device number 2 using dwc2
[  140.689800] usb 1-1: reset high-speed USB device number 2 using dwc2
[  171.649800] usb 1-1: reset high-speed USB device number 2 using dwc2
[  196.179680] random: crng init done
[  202.389799] usb 1-1: reset high-speed USB device number 2 using dwc2
[  233.089793] usb 1-1: reset high-speed USB device number 2 using dwc2
[  263.809864] usb 1-1: reset high-speed USB device number 2 using dwc2
[  274.369825] usb 1-1: reset high-speed USB device number 2 using dwc2
[  305.409813] usb 1-1: reset high-speed USB device number 2 using dwc2
[  336.129807] usb 1-1: reset high-speed USB device number 2 using dwc2
[  366.849811] usb 1-1: reset high-speed USB device number 2 using dwc2
[  397.569813] usb 1-1: reset high-speed USB device number 2 using dwc2
[  428.289827] usb 1-1: reset high-speed USB device number 2 using dwc2
[  435.829806] usb 1-1: reset high-speed USB device number 2 using dwc2
[  444.730040] usb 1-1: USB disconnect, device number 2-----------------------------拔出USB网卡后能继续走下去
.......
系统起来后再插上usb网卡能正常使用。

手上有几款USB网卡，都一直使用正常，rtl8192eu\rtl8723du\rtl8822bu，都使用正常，rtl8821cu这款比较特殊，据说是内置了windows的驱动，会先被识别为存储盘（或者cdrom），需要用到usb_modeswitch来切换为网卡模式。

**Comment by phpnginx** [comment]
拆开网卡看看里面有没有个开关，有的话拨一下应该能解决

**Comment by wellexp** [comment]
重新编译驱动就正常了，可能是升级内核6.x后，用的还是5.x编译出来的内核
