### ISSUE TITLE
请问下之前/boot分区有一键写入emmc脚本，install.sh，怎么现在没有了？

### ISSUE THREAD

**Issue by fvlw** [hzyitc/armbian-onecloud#169]
Armbian_23.08.0-trunk_Onecloud_bookworm_current_6.1.51_minimal.img，下载的是这个镜像，之前我记得/boot/install/下面有个install.sh，怎么现在没有了。不提供了吗 ？
![图片](https://github.com/hzyitc/armbian-onecloud/assets/71577616/77bde8ae-5dd0-45c3-9210-173eca2728d8)

我使用armbian提供的armbian-install也没用。

**Comment by neomikanagi** [comment]
不仅没有了，把之前的下下来还不能用了。

**Comment by hzyitc** [comment]
我的固件从来就没有这个啊，你用的应该是别人做的。

armbian-install不能用估计是缺失uboot或者分区表错了。这个等我有空的话再看看。
