### ISSUE TITLE
cpu最高频率设置不同，网速也不同。

### ISSUE THREAD

**Issue by ghost** [hzyitc/armbian-onecloud#177]
性能模式最高频率1500，网速最高700Mb/s，
节能模式最高频率600，网速最高170Mb/s，
我是1.0版的，网卡驱动还是有问题。

**Comment by bcdi** [comment]
@GlockerYoung 
Hi，最新固件是否还有这个问题

**Comment by bcdi** [comment]
或者可以试试 schedutil 调频方案？
