### ISSUE TITLE
如何从u盘启动

### ISSUE THREAD

**Issue by hurriedlu** [hzyitc/armbian-onecloud#178]
大佬应该怎样设置才可以让玩客云从U盘启动？搜了一圈没搜明白，要是有知道的大佬麻烦解答一下

**Comment by hzyitc** [comment]
刷了我的uboot后就可以啊。启动顺序为：USB、SD、eMMC。

**Comment by bcdi** [comment]
@hzyitc 大佬，直刷包含了你的uboot吧
那么，刷了burn直刷包，启动顺序是不是也这样usb -> sd -> emmc

对usb|sd里的固件，有什么要求吗
刚试了下，emmc刷的您的burn包，sd里烧录了lede上的openwrt，似乎没法启动sd里的固件

**Comment by bcdi** [comment]
> 刚试了下，emmc刷的您的burn包，sd里烧录了lede上的openwrt，似乎没法启动sd里的固件

搞清了，那边的 bootscript 问题，写死了只能 /dev/mmcblk1p2

自己修改了下，重新 mkimage 生成下就好了了
