### ISSUE TITLE
编译后img文件很大

### ISSUE THREAD

**Issue by ghp3000** [hzyitc/armbian-onecloud#179]
编译命令:./compile.sh build BOARD=onecloud BRANCH=edge BUILD_DESKTOP=no BUILD_MINIMAL=yes BUILD_ONLY=no KERNEL_CONFIGURE=no RELEASE=jammy
编译后产物大小:Fast-moving file to output/images [ -> Armbian-unofficial_24.2.0-trunk_Onecloud_jammy_edge_6.6.5_minimal.img (1.17GiB) ]
相比较https://github.com/hzyitc/armbian-onecloud/releases下载解压的文件691M大了很多.
请教一下,是up主有重新调整配置文件吗,如果是,能否分享配置文件.
谢谢.

**Comment by hzyitc** [comment]
release里是GHA自动编译的。脚本在这：https://github.com/hzyitc/armbian-onecloud/blob/readme/.github/workflows/ci.yml
