### ISSUE TITLE
fork了armbian官方仓库，但是机型找不到玩客云

### ISSUE THREAD

**Issue by weigeloveu** [hzyitc/armbian-onecloud#18]
fork了armbian官方仓库，但是机型找不到玩客云，要怎么用官方仓库编译啊

**Comment by MDCY9008** [comment]
参考```workflow```的
https://github.com/hzyitc/armbian-onecloud/blob/readme/.github/workflows/ci.yml
![image](https://user-images.githubusercontent.com/54255527/180982274-4ccf8b79-587d-4be7-9633-7e8bbe9edc07.png)

**Comment by weigeloveu** [comment]
> 参考`workflow`的 https://github.com/hzyitc/armbian-onecloud/blob/readme/.github/workflows/ci.yml ![image](https://user-images.githubusercontent.com/54255527/180982274-4ccf8b79-587d-4be7-9633-7e8bbe9edc07.png)

多谢大佬，我看有编译好的release包，这个包是线刷包吗？

**Comment by hzyitc** [comment]
`onecloud`属于`CSC`(`Community Supported`, `社区支持`)。

需要在下面选择`Show CSC/WIP/EOS`才会显示。

**Comment by hzyitc** [comment]
> > 参考`workflow`的 https://github.com/hzyitc/armbian-onecloud/blob/readme/.github/workflows/ci.yml ![image](https://user-images.githubusercontent.com/54255527/180982274-4ccf8b79-587d-4be7-9633-7e8bbe9edc07.png)
> 
> 多谢大佬，我看有编译好的release包，这个包是线刷包吗？

不是，只是单纯的`磁盘镜像文件`。

`直刷包`还在测试。
