### ISSUE TITLE
如何从U盘启动armbian,哪个镜像是刷U盘启动的。

### ISSUE THREAD

**Issue by nkxhl** [hzyitc/armbian-onecloud#183]
如题

**Comment by lanlanpy** [comment]
不带burn的 ，前提是要刷 大佬的 uboot emmc burn

**Comment by nkxhl** [comment]
> 不带burn的 ，前提是要刷 大佬的 uboot emmc burn

谢谢指导，请问在哪里下载 uboot emmc burn

**Comment by nkxhl** [comment]
> 不带burn的 ，前提是要刷 大佬的 uboot emmc burn

找到了，谢谢啦。下载地址：https://github.com/hzyitc/u-boot-onecloud/releases/download/build-20221028-0940/eMMC.burn.img
