### ISSUE TITLE
如何将玩客云armbian网口调整为千兆速率

### ISSUE THREAD

**Issue by daopica** [hzyitc/armbian-onecloud#185]
固件:Armbian-unofficial_23.11.0-trunk_Onecloud_bookworm_current_6.1.63.burn.img
硬件:短接点在显示灯一侧版本

ethtool eth0检查后网口为百兆
![IMG_20240228_154108.jpg](https://github.com/hzyitc/armbian-onecloud/assets/122165912/7567ed1b-e623-479b-a83e-7f7dd8d388c3)
经过尝试通过命令修改网口速度，会造成重启，重启后依旧百兆。

通过对网络测速如下显示
![IMG_20240228_154248.jpg](https://github.com/hzyitc/armbian-onecloud/assets/122165912/2236234c-957d-453e-b318-e1258c758b87)

请问朋友们有解决分享的么？

**Comment by daopica** [comment]
解决了，换根网线。![IMG_20240302_133353.jpg](https://github.com/hzyitc/armbian-onecloud/assets/122165912/a92f092b-8dd8-4eed-a2cd-f2d455b87469)

**Comment by hzyitc** [comment]
网线问题，速率自动协商的。
