### ISSUE TITLE
有无新手刷机教程

### ISSUE THREAD

**Issue by aotian16** [hzyitc/armbian-onecloud#187]
我看到网上有说要先刷入安卓的，也有说可以直接刷的，不知道那个对的。

**Comment by yulinsoft** [comment]
先插双公头线，再按住reset后通电就可直刷，如果不能识别就要拆机短接。

**Comment by aotian16** [comment]
> 先插双公头线，再按住reset后通电就可直刷，如果不能识别就要拆机短接。

感谢，我试试

**Comment by hzyitc** [comment]
这网上搜一下吧，有不少教程的。
