### ISSUE TITLE
感谢大佬为玩客云付出这么多，经过一晚上的研究，我来写一篇简单入门教程吧

### ISSUE THREAD

**Issue by weigeloveu** [hzyitc/armbian-onecloud#19]
## 大佬的release分为u盘启动包和直刷包，下面主要说一下u盘启动包，下载下来之后直接用rufus写入u盘
# 1.先刷“u盘启动/emmc启动”自动识别底包，推荐大佬编译的eMMC.burn.img
`https://github.com/hzyitc/u-boot-onecloud`
# 2.想要写入emmc的，下载下面的文件，放入u盘的boot分区
`https://github.com/raysworld/onecloud-emmc-install`
## 整个仓库拉下来，重命名为install，放入boot分区，u盘系统启动后 
```
cd /boot/install
./install.sh
```
# 3.直刷包我测试用2.1.6.8的usb burning可以正常刷入。2.2.4会卡在98%不动，然后提示roofs校验失败。是usb burning校验等待超时引起的，ttl里显示rom实际已经烧录成功，主板为1.3版。

**Comment by weigeloveu** [comment]
一大早起来就发现大佬出直刷包了，感谢大佬连夜测试奋战

**Comment by qwasddd** [comment]
> 大佬的release是u盘启动包，下载下来之后直接用rufus写入u盘 u盘启动emmc启动自动识别底包 https://github.com/hzyitc/u-boot-onecloud 想要写入emmc的，下载下面的文件，放入u盘的boot分区 写入emmc脚本 https://github.com/raysworld/onecloud-emmc-install 整个仓库拉下来，重命名为install，放入boot分区 u盘系统启动后 cd /boot/install ./install.sh

下那个的，eMMC.burn.img这个吗，不能直接线刷进去的吗

**Comment by weigeloveu** [comment]
> > 大佬的release是u盘启动包，下载下来之后直接用rufus写入u盘 u盘启动emmc启动自动识别底包 https://github.com/hzyitc/u-boot-onecloud 想要写入emmc的，下载下面的文件，放入u盘的boot分区 写入emmc脚本 https://github.com/raysworld/onecloud-emmc-install 整个仓库拉下来，重命名为install，放入boot分区 u盘系统启动后 cd /boot/install ./install.sh
> 
> 下那个的，eMMC.burn.img这个吗，不能直接线刷进去的吗

我写教程的时候还没有线刷包，现在有了。

**Comment by qwasddd** [comment]
我把这个eMMC.burn.img用USB buring tool刷进玩客云，怎么引导不了U盘的系统，难道还有别的要刷的吗

**Comment by trdmm** [comment]
U盘启动包和直刷包有什么区别吗
