### ISSUE TITLE
插上腾达U2无线网卡，系统无法启动

### ISSUE THREAD

**Issue by Tuya-samson** [hzyitc/armbian-onecloud#191]
插上腾达U2无线网卡后，显示打印从USB启动，然后一直卡住。
拔掉U2重新上电，启动正常，再插上U2，可以正常工作。

除了修改默认引导方式还有方法吗？

**Comment by hzyitc** [comment]
有些网卡好像是会做u盘的，启动时会尝试从那引导，目前暂时没法。

**Comment by Tuya-samson** [comment]
多谢回复！
那再请问下如何修改默认从emmc启动呢？
没太看懂这个说明 [如何从boot启动](https://github.com/hzyitc/armbian-onecloud/blob/readme/README_zh.md#%E5%A6%82%E4%BD%95%E4%BB%8Eu-boot%E5%90%AF%E5%8A%A8)

**Comment by Tuya-samson** [comment]
摸索了一个方法，希望能帮助需要的人
需要接上板子的串口，看到`Hit Enter key to stop autoboot -- :  3`时敲回车
然后输入
```
setenv bootcmd 'run boot_emmc_armbian'
saveenv
```
这样就是只从emmc启动了
注意：以上操作需要备份，有可能造成系统无法启动
