### ISSUE TITLE
玩客云玩的不亦乐乎，手头还有几个赚钱宝PRO，哪位有能用的包分享下？

### ISSUE THREAD

**Issue by drw2005** [hzyitc/armbian-onecloud#198]
闲置的几个赚钱宝，有没有大佬移植好的包分享下啊？
感谢感谢！

**Comment by shinyicn** [comment]
912的包很多，o

**Comment by drw2005** [comment]
> 912的包很多，o

给指个路吧，谢谢！

**Comment by shinyicn** [comment]
搜一下Ophub armbian

**Comment by onetosan** [comment]
> 搜一下Ophub armbian

Ophub的项目是amlogic-s9xxx系列的，而玩客云是amlogic-s8xxx系列的。
为什么网络上总有你这种说话从不自己验证的蠢货呢？
