### ISSUE TITLE
RTL8211F rate 100M normal, 1000M abnormal

### ISSUE THREAD

**Issue by soulant** [hzyitc/armbian-onecloud#2]
Board: v1.3
USB-OS: Armbian_22.05.0-trunk_Onecloud_focal_current_5.14.21
-----------------------------------------------------------

root@onecloud:~# ethtool eth0|grep Speed
        Speed: 1000Mb/s
root@onecloud:~# iperf3 -c 10.0.0.71 -t 5
Connecting to host 10.0.0.71, port 5201
[  5] local 10.0.0.168 port 46580 connected to 10.0.0.71 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   126 KBytes  1.03 Mbits/sec   11   1.41 KBytes
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    4   1.41 KBytes
[  5]   2.00-3.00   sec  41.0 KBytes   336 Kbits/sec    6   1.41 KBytes
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-5.00   sec   167 KBytes   273 Kbits/sec   22             sender
[  5]   0.00-5.00   sec   127 KBytes   208 Kbits/sec                  receiver
iperf Done.

root@onecloud:~# iperf3 -s
Server listening on 5201
Accepted connection from 10.0.0.71, port 44558
[  5] local 10.0.0.168 port 5201 connected to 10.0.0.71 port 44560
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   107 MBytes   899 Mbits/sec
[  5]   1.00-2.00   sec   103 MBytes   860 Mbits/sec
[  5]   2.00-3.00   sec   109 MBytes   912 Mbits/sec
[  5]   3.00-4.00   sec   109 MBytes   912 Mbits/sec
[  5]   4.00-5.00   sec   109 MBytes   912 Mbits/sec
[  5]   5.00-5.01   sec   317 KBytes   449 Mbits/sec
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-5.01   sec   536 MBytes   898 Mbits/sec                  receiver
Server listening on 5201

root@onecloud:~# ethtool -s eth0 speed 100 duplex full autoneg on
root@onecloud:~# ethtool eth0|grep Speed
        Speed: 100Mb/s
root@onecloud:~# iperf3 -c 10.0.0.71 -t 5
Connecting to host 10.0.0.71, port 5201
[  5] local 10.0.0.168 port 46584 connected to 10.0.0.71 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  11.4 MBytes  95.8 Mbits/sec    0   97.6 KBytes
[  5]   1.00-2.00   sec  11.4 MBytes  95.4 Mbits/sec    0    115 KBytes
[  5]   2.00-3.00   sec  11.2 MBytes  93.8 Mbits/sec    0    126 KBytes
[  5]   3.00-4.00   sec  11.3 MBytes  94.8 Mbits/sec    0    126 KBytes
[  5]   4.00-5.00   sec  11.1 MBytes  93.3 Mbits/sec    0    126 KBytes
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-5.00   sec  56.4 MBytes  94.6 Mbits/sec    0             sender
[  5]   0.00-5.01   sec  56.2 MBytes  94.1 Mbits/sec                  receiver
iperf Done.

root@onecloud:~# iperf3 -s
Server listening on 5201
Accepted connection from 10.0.0.71, port 44562
[  5] local 10.0.0.168 port 5201 connected to 10.0.0.71 port 44564
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  11.2 MBytes  94.0 Mbits/sec
[  5]   1.00-2.00   sec  11.2 MBytes  94.1 Mbits/sec
[  5]   2.00-3.00   sec  11.2 MBytes  94.1 Mbits/sec
[  5]   3.00-4.00   sec  11.2 MBytes  94.1 Mbits/sec
[  5]   4.00-5.00   sec  11.2 MBytes  94.1 Mbits/sec
[  5]   5.00-5.00   sec  29.7 KBytes  82.3 Mbits/sec
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-5.00   sec  56.1 MBytes  94.1 Mbits/sec                  receiver

**Comment by hzyitc** [comment]
Fail to reproduce in `edge`

I will use `current` to test

```
root@onecloud:~# iperf3 -c * -R
Connecting to host *, port 5201
Reverse mode, remote host * is sending
[  5] local * port 51806 connected to * port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   100 MBytes   840 Mbits/sec
[  5]   1.00-2.00   sec   107 MBytes   893 Mbits/sec
[  5]   2.00-3.00   sec   111 MBytes   934 Mbits/sec
[  5]   3.00-4.00   sec   108 MBytes   908 Mbits/sec
[  5]   4.00-5.00   sec   108 MBytes   906 Mbits/sec
[  5]   5.00-6.00   sec   108 MBytes   907 Mbits/sec
[  5]   6.00-7.00   sec   105 MBytes   880 Mbits/sec
[  5]   7.00-8.00   sec   110 MBytes   921 Mbits/sec
[  5]   8.00-9.00   sec   107 MBytes   901 Mbits/sec
[  5]   9.00-10.00  sec   107 MBytes   897 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.05 GBytes   901 Mbits/sec   45             sender
[  5]   0.00-10.00  sec  1.05 GBytes   899 Mbits/sec                  receiver

iperf Done.
```

```
root@onecloud:~# iperf3 -c *
Connecting to host *, port 5201
[  5] local * port 51802 connected to * port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  27.9 MBytes   234 Mbits/sec  123   21.2 KBytes
[  5]   1.00-2.00   sec  31.7 MBytes   266 Mbits/sec  111   26.9 KBytes
[  5]   2.00-3.00   sec  29.0 MBytes   243 Mbits/sec  108   33.9 KBytes
[  5]   3.00-4.00   sec  27.1 MBytes   227 Mbits/sec   92   36.8 KBytes
[  5]   4.00-5.00   sec  25.0 MBytes   210 Mbits/sec   99   24.0 KBytes
[  5]   5.00-6.00   sec  28.2 MBytes   237 Mbits/sec   96   21.2 KBytes
[  5]   6.00-7.00   sec  31.1 MBytes   261 Mbits/sec  131   11.3 KBytes
[  5]   7.00-8.00   sec  29.3 MBytes   245 Mbits/sec  108    103 KBytes
[  5]   8.00-9.00   sec  32.8 MBytes   275 Mbits/sec  110   21.2 KBytes
[  5]   9.00-10.00  sec  34.3 MBytes   287 Mbits/sec  105   21.2 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   296 MBytes   249 Mbits/sec  1083             sender
[  5]   0.00-10.00  sec   296 MBytes   248 Mbits/sec                  receiver

iperf Done.
```

**Comment by hzyitc** [comment]
Also, someone point that some problems about `ethernet` may due to the `u-boot`. I use `s805_flash_snail.img`

**Comment by soulant** [comment]
s805_flash_snail.img and uboot v1.0 
The test results are all 1000M abnormal, but the kernel 3.x is basically normal.

**Comment by hzyitc** [comment]
What's more, using `/dev/zero` instand of `random data` can speed up.

```
root@onecloud:~# iperf3 -c ip -F /dev/zero
Connecting to host ip, port 5201
[  5] local ip port 48466 connected to ip port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  93.7 MBytes   782 Mbits/sec   12    202 KBytes
[  5]   1.00-2.00   sec  83.9 MBytes   704 Mbits/sec    7    181 KBytes
[  5]   2.00-3.00   sec  89.2 MBytes   749 Mbits/sec   10   93.3 KBytes
[  5]   3.00-4.00   sec  85.6 MBytes   721 Mbits/sec   10    243 KBytes
[  5]   4.00-5.00   sec  81.0 MBytes   679 Mbits/sec   15    223 KBytes
[  5]   5.00-6.00   sec  90.5 MBytes   759 Mbits/sec    9    249 KBytes
[  5]   6.00-7.00   sec  90.0 MBytes   754 Mbits/sec   11    170 KBytes
[  5]   7.00-8.00   sec  84.2 MBytes   706 Mbits/sec   11    226 KBytes
[  5]   8.00-9.00   sec  87.4 MBytes   732 Mbits/sec   10    184 KBytes
[  5]   9.00-10.00  sec  86.2 MBytes   725 Mbits/sec   14    221 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   872 MBytes   731 Mbits/sec  109             sender
        Sent  872 MByte / 0.00 Byte (100%) of /dev/zero
[  5]   0.00-10.01  sec   871 MBytes   730 Mbits/sec                  receiver

iperf Done.
```

```
root@onecloud:~# iperf3 -c ip -F /dev/zero -R
Connecting to host ip, port 5201
Reverse mode, remote host ip is sending
[  5] local ip port 48470 connected to ip port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   109 MBytes   911 Mbits/sec
[  5]   1.00-2.00   sec   110 MBytes   921 Mbits/sec
[  5]   2.00-3.00   sec   108 MBytes   904 Mbits/sec
[  5]   3.00-4.00   sec   110 MBytes   923 Mbits/sec
[  5]   4.00-5.00   sec   110 MBytes   922 Mbits/sec
[  5]   5.00-6.00   sec   110 MBytes   923 Mbits/sec
[  5]   6.00-7.00   sec   104 MBytes   874 Mbits/sec
[  5]   7.00-8.00   sec   105 MBytes   886 Mbits/sec
[  5]   8.00-9.00   sec   110 MBytes   919 Mbits/sec
[  5]   9.00-10.00  sec   102 MBytes   849 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.01  sec  1.06 GBytes   909 Mbits/sec   33             sender
        Sent 1.05 GByte / 0.00 Byte (100%) of /dev/zero
[  5]   0.00-10.00  sec  1.05 GBytes   903 Mbits/sec                  receiver

iperf Done.
```

**Comment by soulant** [comment]
But I use scp to transfer files very very slow

```
root@onecloud:~# dd if=/dev/zero of=test.img bs=1M count=512
512+0 records in
512+0 records out
root@onecloud:~# scp test.img root@10.0.0.71:/root
root@10.0.0.71's password:
test.img                                                                1% 8848KB 336.9KB/s   25:29 ETA
```

**Comment by hzyitc** [comment]
Due to i can't reproduce, so i can't help anymore.

Please try to reflash `u-boot`

**Comment by soulant** [comment]
Test http real files by wget:
```
[root@bogon ~]# wget http://10.0.0.168:/Armbian_22.08.0-trunk_Onecloud_focal_current_5.14.21.img
--2022-06-05 16:27:06--  http://10.0.0.168/Armbian_22.08.0-trunk_Onecloud_focal_current_5.14.21.img
Connecting to 10.0.0.168:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1652555776 (1.5G)
Saving to: ‘Armbian_22.08.0-trunk_Onecloud_focal_current_5.14.21.img’

 1% [                                                               ] 20,069,008   831KB/s  eta 21m 43s

# Switch 100M
88% [=======================================>       ] 1,464,912,368 9.05MB/s  eta 19s

# Linux onecloud 3.10
20% [============>                                                  ] 346,861,840 36.1MB/s  eta 36s
```

# The cable is ok，uboot: v1.0 and s805_flash_snail.img
In short, the actual use of transfer files on high kernel 1G is very low

**Comment by hzyitc** [comment]
Well, when i try to transplant `u-boot`, I notice that the 1000M and 100M ethernet may use diff clk. Also the clk was init by `u-boot`. So the problems maybe the `u-boot` or the hardware.

Please check the `packet error rate`, If high, maybe the clk was wrong.

You can use `clkmsr` in `u-boot` to check the clk. It will show `[ 125 MHz]  CTS_ETH_RMII(11)`. Note: it may not very accurate. I try to adjust the code, but it not change.

Also, you can try to use `ping` in `u-boot`

**Comment by soulant** [comment]
clkmsr in uboot:
[ 125 MHz] CTS_ETH_RMII(11)

**Comment by soulant** [comment]
test empty.img or change rate 100M
The speed is normal
wget http://10.0.0.168/empty.img

but realfile.img
The speed is abnormal
wget http://10.0.0.168/Armbian_22.08.0-trunk_Onecloud_focal_current_5.14.21.img

```
root@onecloud:~# ifconfig eth0| tail -6
        RX packets 1383733  bytes 1746029081 (1.7 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1760217  bytes 2598806816 (2.5 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 37
```

**Comment by soulant** [comment]
boot mac is randomly
Suggest fix mac
e.g. meson8b-odroid1.dts
&efuse {
        ethernet_mac_address: mac@1b4 {
                reg = <0x1b4 0x6>;
        };
};

ethmac {
       nvmem-cells = <&ethernet_mac_address>;
       nvmem-cell-names = "mac-address";
}

fix dmesg  VCC5V: disabling
Suggest remove or introduce into 3V3 1V8

**Comment by soulant** [comment]
It seems that only the RMII external clock source is defined in u-boot, and there is no RGMII clock source

**Comment by soulant** [comment]
I follow the official manual (Amlogic Ethenet controller user Guide.pdf), still the same effect

**Comment by hzyitc** [comment]
you can try to adjust the `clk`

**Comment by hzyitc** [comment]
```
	SET_CBUS_REG_MASK(HHI_GEN_CLK_CNTL, 
	(3<<0) // CLK_DIV: 3+1=4
	| (1<<11) // CLK_EN
	| (11<<12) // CLK_SEL: fclk_div5?
	);
	SET_CBUS_REG_MASK(HHI_MPLL_CNTL6, 1<<27); // CKEN[4]: MPLL output DIV2 enable
	SET_CBUS_REG_MASK(HHI_MPLL_CNTL9,  // 2550/(5+1638/16384)=500Mhz
		(1638<<0) // sdm_in
		| (1<<14) // en_dds2
		| (1<<15) // sdn_en2
		| (5<<16) // n_in2
		| (0<<25) // lp_en2
		| (0<<26) // ir_byin2
		| (0<<30) // modlsel2
		| (0<<31) // ir_bypass2
		);
```

**Comment by hzyitc** [comment]
I'm not sure which `mac` use. `DIV2` or `MPLL2`

**Comment by hzyitc** [comment]
```
	SET_CBUS_REG_MASK(PERIPHS_PIN_MUX_6, 0x3f4f);
	SET_CBUS_REG_MASK(PERIPHS_PIN_MUX_7, 0xf00000);
	eth_reg0.d32 = 0;
	eth_reg0.b.phy_intf_sel = 1; // RGMII
	eth_reg0.b.data_endian = 0; // transfer data in little-endian
	eth_reg0.b.desc_endian = 0; // transfer descriptor in the same endian as the data
	eth_reg0.b.rx_clk_rmii_invert = 0; // For RGMII, use RX_CLK
	eth_reg0.b.rgmii_tx_clk_src = 0;  // Unused
	eth_reg0.b.rgmii_tx_clk_phase = 1; // TX_CLK delay 1/4 cycle
	eth_reg0.b.rgmii_tx_clk_ratio = 2; // MPLL2 is 500MHz
	eth_reg0.b.phy_ref_clk_enable = 1; // Generate 25MHz clock for PHY
	eth_reg0.b.clk_rmii_i_invert = 1; // Use inverted clk_rmii_i to generate 25/2.5 tx_rx_clk
	eth_reg0.b.clk_en = 1; // Enable TX_CLK and PHY_REF_CLK generator
	eth_reg0.b.adj_enable = 1; // Enable data delay adjustment and calibration logic
	eth_reg0.b.adj_setup = 1; // auto delay and skew the RXDV and RXD setup time
	eth_reg0.b.adj_delay = 0; // Capture input data at this clock index
	eth_reg0.b.adj_skew = 0; // 5 bits correspondent to {RXDV, RXD[3:0]}
	eth_reg0.b.cali_start = 0; // Not to start calibration logic
	eth_reg0.b.cali_rise = 0; // test fallng edge
	eth_reg0.b.cali_sel = 0; // Select one signal from {RXDV, RXD[3:0]} to calibrate
	eth_reg0.b.rgmii_rx_reuse = 0; // Not to use RX_CLK as TX_CLK
	eth_reg0.b.eth_urgent = 0; // Not to set AHB to DDR interface as urgent
	WRITE_CBUS_REG(PREG_ETHERNET_ADDR0, eth_reg0.d32);// rgmii mode
```

**Comment by soulant** [comment]
The official manual says that mpll2 is the only clock for Ethernet
But after I disable DIV2, only modifying MPLL2 still has no effect
After the clock frequency is modified, it cannot be detected in uboot (it seems that there is only RMII in uboot)
Modified definition RGMII test results are the same as unmodified
I don't think it's caused by the uboot clk, Because using 3.10 kernel speed is normal
I think the clk configuration of the 5.x kernel isn’t  compatible enough on the board v1.3

**Comment by hzyitc** [comment]
How did you use `3.10`? Just modify `/config/source/` or any thing else?

**Comment by hzyitc** [comment]
`DIV2` doesn`t seem to relative to the `ethernet`. But when disabling it, the `ethernet` doesn't work in `u-boot`. Also it may not `DIV2`due to all of these register haven't described well in `S805` manual. Some description I used are from `S905` manual.

**Comment by soulant** [comment]
The kernel 3.10 comes from the onecloud's system
I also compiled the 4.19 kernel, but the network PHY can't be loaded normally，I also can't test iperf3

**Comment by soulant** [comment]
The kernel 4.19 test results are still the same。

**Comment by hzyitc** [comment]
> 

The original system?

**Comment by hzyitc** [comment]
Please check `cat /sys/kernel/debug/clk/c9410000.ethernet#*/clk_rate`

**Comment by hzyitc** [comment]
Which `branch` do yo use? I use `edge`

**Comment by soulant** [comment]
alpine

**Comment by hzyitc** [comment]
Use the `edge` to check the `clk`.

Without sources, the original kernel may not help.

**Comment by soulant** [comment]
I can only try it, it may not be able to load the system normally.
Armbian_22.08.0-trunk_Onecloud_focal_current_5.14.21.img can't load on 3.x

**Comment by soulant** [comment]
> Use the `edge` to check the `clk`.
> 
> Without sources, the original kernel may not help anything.

Ok, I'll test it when I can drive it

**Comment by hzyitc** [comment]
```
          mpll_prediv                 1        1        0  2550000000          0     0  50000         Y
             mpll0_div                0        0        0           0          0     0  50000         Y
                mpll0                 0        0        0           0          0     0  50000         N
             mpll1_div                0        0        0           0          0     0  50000         Y
                mpll1                 0        0        0           0          0     0  50000         N
             mpll2_div                1        1        0   499996410          0     0  50000         Y
                mpll2                 1        1        0   499996410          0     0  50000         Y
                   c9410000.ethernet#m250_sel       1        1        0   499996410          0     0  50000         Y
                      c9410000.ethernet#m250_div       1        1        0   249998205          0     0  50000         Y
                         c9410000.ethernet#fixed_div2       1        1        0   124999102          0     0  50000         Y
                            c9410000.ethernet#rgmii_tx_en       1        1        0   124999102          0     0  50000         Y
```

**Comment by soulant** [comment]
```
root@onecloud:~# cat /sys/kernel/debug/clk/c9410000.ethernet#*/clk_rate
124999102
249998205
499996410
124999102
root@onecloud:~#

cat /sys/kernel/debug/clk/clk_summary
          mpll_prediv                 1        1        0  2550000000          0     0  50000         Y
             mpll0_div                0        0        0   294911307          0     0  50000         Y
                mpll0                 0        0        0   294911307          0     0  50000         N
             mpll1_div                0        0        0   270948663          0     0  50000         Y
                mpll1                 0        0        0   270948663          0     0  50000         N
             mpll2_div                1        1        0   499996410          0     0  50000         Y
                mpll2                 1        1        0   499996410          0     0  50000         Y
                   c9410000.ethernet#m250_sel       1        1        0   499996410          0     0  50000         Y
                      c9410000.ethernet#m250_div       1        1        0   249998205          0     0  50000         Y
                         c9410000.ethernet#fixed_div2       1        1        0   124999102          0     0  50000         Y
                            c9410000.ethernet#rgmii_tx_en       1        1        0   124999102          0     0  50000         Y

```

**Comment by hzyitc** [comment]
I find something strange.

[drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L32](https://github.com/torvalds/linux/blob/7d2a07b769330c34b4deabeed939325c77a7ec2f/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L32)
```
/* mux to choose between fclk_div2 (bit unset) and mpll2 (bit set) */
#define PRG_ETH0_CLK_M250_SEL_MASK	GENMASK(4, 4)
```

[drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L147](https://github.com/torvalds/linux/blob/7d2a07b769330c34b4deabeed939325c77a7ec2f/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L147)
```
static const struct clk_parent_data mux_parents[] = {
		{ .fw_name = "clkin0", },
		{ .index = -1, },
	};
```

[arch/arm/boot/dts/meson8b.dtsi#L499](https://github.com/torvalds/linux/blob/7d2a07b769330c34b4deabeed939325c77a7ec2f/arch/arm/boot/dts/meson8b.dtsi#L499)
```
&ethmac {
	compatible = "amlogic,meson8b-dwmac", "snps,dwmac-3.70a", "snps,dwmac";

	reg = <0xc9410000 0x10000
	       0xc1108140 0x4>;

	clocks = <&clkc CLKID_ETH>,
		 <&clkc CLKID_MPLL2>,
		 <&clkc CLKID_MPLL2>,
		 <&clkc CLKID_FCLK_DIV2>;
	clock-names = "stmmaceth", "clkin0", "clkin1", "timing-adjustment";
```

So maybe use the incorrent clock.

**Comment by soulant** [comment]
I also think it is not to change uboot, it is only abnormal on high kernel.

**Comment by soulant** [comment]
Yesterday I also removed this <&clkc CLKID_FCLK_DIV2>，but invalid.

**Comment by hzyitc** [comment]
Yes, I was misdirected by some old threads.

**Comment by soulant** [comment]
s805 manual says that mpll2 is the only，but `Amlogic Ethenet controller user Guide.pdf ` are using div2

**Comment by hzyitc** [comment]
The `timing-adjustment` may effect nothing. Due to `rx-internal-delay-ps` isn't set to 2.

[drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L435](https://github.com/torvalds/linux/blob/7d2a07b769330c34b4deabeed939325c77a7ec2f/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L435)
```
	/* RX delay defaults to 0ps since this is what many boards use */
	if (of_property_read_u32(pdev->dev.of_node, "rx-internal-delay-ps",
				 &dwmac->rx_delay_ps)) {
		if (!of_property_read_u32(pdev->dev.of_node,
					  "amlogic,rx-delay-ns",
					  &dwmac->rx_delay_ps))
			/* convert ns to ps */
			dwmac->rx_delay_ps *= 1000;
	}
```

[drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L292](https://github.com/torvalds/linux/blob/7d2a07b769330c34b4deabeed939325c77a7ec2f/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L292)
```
	if (dwmac->data->has_prg_eth1_rgmii_rx_delay)
		cfg_rxclk_dly = FIELD_PREP(PRG_ETH1_CFG_RXCLK_DLY,
					   dwmac->rx_delay_ps / 200);
	else if (dwmac->rx_delay_ps == 2000)
		rx_adj_config = PRG_ETH0_ADJ_ENABLE | PRG_ETH0_ADJ_SETUP;
```

[drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L320](https://github.com/torvalds/linux/blob/7d2a07b769330c34b4deabeed939325c77a7ec2f/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c#L320)

```
	if (delay_config & PRG_ETH0_ADJ_ENABLE) {
		if (!dwmac->timing_adj_clk) {
			dev_err(dwmac->dev,
				"The timing-adjustment clock is mandatory for the RX delay re-timing\n");
			return -EINVAL;
		}

		/* The timing adjustment logic is driven by a separate clock */
		ret = meson8b_devm_clk_prepare_enable(dwmac,
						      dwmac->timing_adj_clk);
		if (ret) {
			dev_err(dwmac->dev,
				"Failed to enable the timing-adjustment clock\n");
			return ret;
		}
	}
```

**Comment by soulant** [comment]
This is not present in earlier configurations (timing-adjustment)

**Comment by hzyitc** [comment]
Please use this `patch` to test.

```
Try to fix ethernet clk

---
 arch/arm/boot/dts/meson8b.dtsi                      | 2 +-
 drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/arch/arm/boot/dts/meson8b.dtsi b/arch/arm/boot/dts/meson8b.dtsi
index 31ba23663b4..de24dda94eb 100644
--- a/arch/arm/boot/dts/meson8b.dtsi
+++ b/arch/arm/boot/dts/meson8b.dtsi
@@ -725,7 +725,7 @@ &ethmac {
 	       0xc1108140 0x4>;
 
 	clocks = <&clkc CLKID_ETH>,
-		 <&clkc CLKID_MPLL2>,
+		 <&clkc CLKID_FCLK_DIV2>,
 		 <&clkc CLKID_MPLL2>,
 		 <&clkc CLKID_FCLK_DIV2>;
 	clock-names = "stmmaceth", "clkin0", "clkin1", "timing-adjustment";
diff --git a/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c b/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c
index c7a6588d939..7e94e8fd72c 100644
--- a/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c
+++ b/drivers/net/ethernet/stmicro/stmmac/dwmac-meson8b.c
@@ -146,7 +146,7 @@ static int meson8b_init_rgmii_tx_clk(struct meson8b_dwmac *dwmac)
 	struct device *dev = dwmac->dev;
 	static const struct clk_parent_data mux_parents[] = {
 		{ .fw_name = "clkin0", },
-		{ .index = -1, },
+		{ .fw_name = "clkin1", },
 	};
 	static const struct clk_div_table div_table[] = {
 		{ .div = 2, .val = 2, },
-- 
2.25.1


```

**Comment by soulant** [comment]
Looks like it's still the same

**Comment by soulant** [comment]
How to boot from u-boot ?
recommend `setenv `instead of `=`
Otherwise there are initial variables which may be invalid!

**Comment by hzyitc** [comment]
> How to boot from u-boot ? recommend `setenv `instead of `=` Otherwise there are initial variables which may be invalid!

Well, the var defined by `setenv` will be saved. So I don't want to do this

**Comment by soulant** [comment]
> > How to boot from u-boot ? recommend `setenv `instead of `=` Otherwise there are initial variables which may be invalid!
> 
> Well, the var defined by `setenv` will be saved. So I don't want to do this

How can it be saved without using saveenv?

**Comment by hzyitc** [comment]
I mean by accident. For example, run `bootscript` but failed. Then the user will try to change something and then `saveenv`.

**Comment by soulant** [comment]
This `rate `problem seems to be related to `EEE `or `macirq`.
The original kernel turned off EEE, but `5.x `has turned on `interrupts = <0x0 0x8 0x4>`; EEE is not needed.
I try put `interrupts = <0x0 0x8 0x1>`, and then turning off EEE is still invalid.

**Comment by soulant** [comment]
> I mean by accident. For example, run `bootscript` but failed. Then the user will try to change something and then `saveenv`.

Interesting, I happen to set the initial variable, which makes it impossible to use.

**Comment by xiaoxia625** [comment]
> 
我也遇到这个问题了，刷的最新的直刷包。

**Comment by xiaoxia625** [comment]
刷3.10内核的openwrt，内网速率正常。

**Comment by hzyitc** [comment]
https://github.com/torvalds/linux/commit/433c6cab9d298687c097f6ee82e49157044dc7c6
https://github.com/torvalds/linux/commit/bd6f48546b9cb7a785344fc78058c420923d7ed8

目前还是怀疑是时钟。

可以注意到你们的测试结果均有重传现象。`iperf3` 的 `Retr` 列即为重传次数。

**Comment by xiaoxia625** [comment]
> 
这个时钟问题该如何解决呢？刚接触这个，不太懂，这个问题是内核的原因导致的还是我机器硬件的原因？要是硬件原因的话，我就不管他了

**Comment by hzyitc** [comment]
找到原因了，`PHY`那边的`TX-delay`好像不太生效。用`MAC`的就行。

```diff
 	pinctrl-names = "default";
 
 	phy-handle = <&eth_phy>;
-	phy-mode = "rgmii-id";
+	phy-mode = "rgmii-rxid";
 
 	mdio {
 		compatible = "snps,dwmac-mdio";
```

**Comment by hzyitc** [comment]
[fix-ethernet-uplink.zip](https://github.com/hzyitc/armbian-onecloud/files/11057794/fix-ethernet-uplink.zip)

麻烦各位测试下给个反馈。

**Comment by k3bc999** [comment]
![图片](https://user-images.githubusercontent.com/27000015/227432780-304a31a2-587d-479c-92f2-8572fca60770.png)
好了好了 修好了！

**Comment by k3bc999** [comment]
对比issue 99

**Comment by soulant** [comment]
Thanks for the fix!
It's very nice!

**Comment by kwxiaozhu** [comment]
![image](https://user-images.githubusercontent.com/7983147/227498525-bbea4e94-892d-491f-a696-76d25388d4dd.png)

测试的最新CI 2023-02-21 12:56:06的烧录镜像，完全正常，非常感谢，吃灰的玩客云又可以利用起来了

**Comment by k3bc999** [comment]
大佬 最近的包 jammy minimal 23.05（03-25）的dtb没改吗？ 还是有问题 改为这里的dtb就好了

**Comment by hzyitc** [comment]
> 大佬 最近的包 jammy minimal 23.05（03-25）的dtb没改吗？ 还是有问题 改为这里的dtb就好了

还没，上游要修的东西有点多。慢慢交PR吧。

**Comment by k3bc999** [comment]
> > 大佬 最近的包 jammy minimal 23.05（03-25）的dtb没改吗？ 还是有问题 改为这里的dtb就好了
> 
> 还没，上游要修的东西有点多。慢慢交PR吧。

了解了 十分感谢
