### ISSUE TITLE
在root下ls命令，文件和文件夹都是显白色，而在普通用户下执行ls命令，文件和文件夹显示正常彩色，这是怎么回事？

### ISSUE THREAD

**Issue by onetosan** [hzyitc/armbian-onecloud#203]
在root下执行ls命令，文件和文件夹都是显白色，而在普通用户下执行ls命令，文件和文件夹显示正常彩色，
但是如果切换到普通用户之后，再切换回root用户再执行ls命令，文件和文件夹就显示正常彩色了。
这是怎么回事？

本人的玩客云刷了好几个包都是一样的故障

ps：另外，在本人的晶晨机顶盒刷armbian没有出现过这种故障

**Comment by hzyitc** [comment]
.bashrc里面alias配置的。
ubuntu默认就是这样。
