### ISSUE TITLE
修改bootargs，实现全程hdmi画面输出

### ISSUE THREAD

**Issue by hkbase** [hzyitc/armbian-onecloud#26]
我在刷入您的Armbian_22.08.0-trunk_Onecloud_jammy_edge_5.18.0_minimal.burn.img和Armbian_22.08.0-trunk_Onecloud_bullseye_edge_5.18.0_minimal.burn.img文件之后，修改了boot.cmd里的引导参数，重新生成boot.scr之后，设备加电开机后，hdmi全程有画面输出，可以看到系统文件的引导过程。
附上我的bootargs参数，供您参考：
rootfstype=ext4 rootflags=data=writeback rootwait rw console=ttyAML0,115200n8 console=tty0 fsck.repair=yes net.ifnames=0 ipv6.disable=1 logo=osd1,loaded,0x7900000,${hdmimode},full
其实这个方法，适用于您的所有镜像版本。

**Comment by hzyitc** [comment]
不错的建议，下次PR加入。

**Comment by hkbase** [comment]
这个方法，适用于您的所有镜像版本。

**Comment by MDCY9008** [comment]
> 不错的建议，下次PR加入。

希望能把ipv6留着

**Comment by hzyitc** [comment]
Add in [Commit 55882dbf](https://github.com/hzyitc/armbian-onecloud/commit/55882dbf9f55709a5512602fc5510029c98642da). Close.

**Comment by jswxll** [comment]
> Add in [Commit 55882dbf](https://github.com/hzyitc/armbian-onecloud/commit/55882dbf9f55709a5512602fc5510029c98642da). Close.

815的版本，这个功能是还没有吗？

**Comment by hzyitc** [comment]
> > Add in [Commit 55882dbf](https://github.com/hzyitc/armbian-onecloud/commit/55882dbf9f55709a5512602fc5510029c98642da). Close.
> 
> 815的版本，这个功能是还没有吗？

有的，但该功能是修改`bootargs`实现的。如果使用第三方卡刷，可能他们并没有添加该`bootargs`

**Comment by jswxll** [comment]
> > > Add in [Commit 55882dbf](https://github.com/hzyitc/armbian-onecloud/commit/55882dbf9f55709a5512602fc5510029c98642da). Close.
> > 
> > 
> > 815的版本，这个功能是还没有吗？
> 
> 有的，但该功能是修改`bootargs`实现的。如果使用第三方卡刷，可能他们并没有添加该`bootargs`

我刷的815，看不到引导过程，开机后到有画面内容是左上角一个-杠，随后是终端登录界面
