### ISSUE TITLE
希望加入usb Wi-Fi驱动支持

### ISSUE THREAD

**Issue by 7ackkkkk** [hzyitc/armbian-onecloud#27]
感谢付出，用到现在最好的版本，直刷真是太方便了！
lsusb能看到wifi，但是nmtui里搜不到无线，麻烦添加一下USB Wi-Fi的支持

**Comment by hzyitc** [comment]
具体的USB WiFi型号？

`kernel` 里面是开启了部分设备的支持的。

我手头没有任何USB WiFi，无法进行测试。

**Comment by pplps** [comment]
支持，之前折腾着搞了挺长时间，只有一个usb口能用，插usb网卡就很鸡肋。在大佬支持完善了wky固件后，两个usb口都能用了之后，就很完美了。恩山有人基于大佬的固件编译了新的固件，很稳定，里面很多常用usb网卡的支持，这是链接
https://www.right.com.cn/forum/thread-4103842-1-2.html
希望大佬能能支持一下，因为焊接wifi模块对玩客云来说有难度，但是usb网口就很轻易，很多人都可以轻松让玩客云用上wifi，网卡也很便宜。

**Comment by 7ackkkkk** [comment]
> 具体的USB WiFi型号？
> 
> `kernel` 里面是开启了部分设备的支持的。
> 
> 我手头没有任何USB WiFi，无法进行测试。

我看了固件自带的驱动比较少，然后尝试编译安装但是linux-header装不上，上面那个恩山的链接好像有附源码，不知道大神能不能整合一下

**Comment by hkbase** [comment]
只需要开启内核支持的wifi网卡芯片驱动支持就够用了。

**Comment by shiyu1314** [comment]
apt install -f

**Comment by wllzhk** [comment]
我也是linux-header装不上，官方的armbian-config找不到对应的header

**Comment by hzyitc** [comment]
Release里面有header的deb包

**Comment by wllzhk** [comment]
> Release里面有header的deb包

谢谢，用dpkg安装了。

**Comment by wllzhk** [comment]
安装header时会断开ssh链接，设备重启后在路由里没有IP
`dpkg -i linux-headers-edge-meson_22.11.0-trunk_armhf.deb 
Selecting previously unselected package linux-headers-edge-meson.
(Reading database ... 39652 files and directories currently installed.)
Preparing to unpack linux-headers-edge-meson_22.11.0-trunk_armhf.deb ...
Unpacking linux-headers-edge-meson (22.11.0-trunk) ...
Setting up linux-headers-edge-meson (22.11.0-trunk) ...
Compiling headers - please wait ...

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(WKY-root) at 10:58:18.

Type `help' to learn how to use Xshell prompt.`

**Comment by cicwangbin2021** [comment]
首先感谢H大的付出。我用的MTK 7601U 的USB-WIFI ,插上可以正常识别，也可以连到自己的无线路由器。但是这个驱动只支持STA,不支持AP模式，无法手机直接连接WKY去打印东西。能不能集成一个带AP模式的驱动？

**Comment by cicwangbin2021** [comment]
首先感谢H大的付出。我用的MTK 7601U 的USB-WIFI ,插上可以正常识别，也可以连到自己的无线路由器。但是这个驱动只支持STA,不支持AP模式，无法手机直接连接WKY去打印东西。能不能集成一个带AP模式的驱动？

**Comment by KayXin** [comment]
我这里有两个usb网卡,360随身wifi2代和一个免驱的8188GU
lsusb出现的信息
ID 0bda:1a2b Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (Driver CDROM Mode)
ID 148f:760b Ralink Technology, Corp. MT7601U Wireless Adapter

360这个是可以设置网卡模式,是可以搜索wifi,并连接使用
8188这个感觉就是当做U盘挂载了,用eject卸载掉之后
 ID 0bda:b711 Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (After Modeswitch)
尝试编译驱动,失败

**Comment by uuxxcccc** [comment]
> 我这里有两个usb网卡,360随身wifi2代和一个免驱的8188GU lsusb出现的信息 ID 0bda:1a2b Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (Driver CDROM Mode) ID 148f:760b Ralink Technology, Corp. MT7601U Wireless Adapter
> 
> 360这个是可以设置网卡模式,是可以搜索wifi,并连接使用 8188这个感觉就是当做U盘挂载了,用eject卸载掉之后 ID 0bda:b711 Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (After Modeswitch) 尝试编译驱动,失败

在相似的折腾道路上浪费了约一个多星期后，我编译通过了8188GU驱动，没啥技术含量，就是拉俄国人的驱动代码仓库，然后在make之前，修改Makefile文件，在第1065行处ARM-RPI段内，插入EXTRA_CFLAGS += -fno-stack-protector，意思是告诉编译器取消堆栈保护检测机制，但加载编译出的8188gu.ko模块之后，基本能用上wifi卡了，只是有不时cpu爆满几乎死机。具体原因搞不清楚，也许就是内存溢出导致的吧？!另外查资料学到了对于这种自带驱动storage的usb网卡，要提前安装usb-modeswitch工具，并添加hotplug事件，否则一插usb就进入存储模式。还有就是要按当前onecloud的linux版本号下载相应的linux-headers并安装，否则编译不了。由于armbian更新内核版本太快太多，导致请别人编译驱动或者直接拿别人的成果，变得实用意义很小，不同版本之间驱动无法通用。所以需要自己编译。

**Comment by hzyitc** [comment]
基本上kernel有的都开了。

**Comment by FreeWillDeveloper** [comment]
> > 我这里有两个usb网卡,360随身wifi2代和一个免驱的8188GU lsusb出现的信息 ID 0bda:1a2b Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (Driver CDROM Mode) ID 148f:760b Ralink Technology, Corp. MT7601U Wireless Adapter
> > 360这个是可以设置网卡模式,是可以搜索wifi,并连接使用 8188这个感觉就是当做U盘挂载了,用eject卸载掉之后 ID 0bda:b711 Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (After Modeswitch) 尝试编译驱动,失败
> 
> 在相似的折腾道路上浪费了约一个多星期后，我编译通过了8188GU驱动，没啥技术含量，就是拉俄国人的驱动代码仓库，然后在make之前，修改Makefile文件，在第1065行处ARM-RPI段内，插入EXTRA_CFLAGS += -fno-stack-protector，意思是告诉编译器取消堆栈保护检测机制，但加载编译出的8188gu.ko模块之后，基本能用上wifi卡了，只是有不时cpu爆满几乎死机。具体原因搞不清楚，也许就是内存溢出导致的吧？!另外查资料学到了对于这种自带驱动storage的usb网卡，要提前安装usb-modeswitch工具，并添加hotplug事件，否则一插usb就进入存储模式。还有就是要按当前onecloud的linux版本号下载相应的linux-headers并安装，否则编译不了。由于armbian更新内核版本太快太多，导致请别人编译驱动或者直接拿别人的成果，变得实用意义很小，不同版本之间驱动无法通用。所以需要自己编译。

你好, 我现在手里有个8188etv的网卡, 怎样通过usb-modeswitch的hotplug切换到网卡模式?

**Comment by uuxxcccc** [comment]
关于如何操控usb modeswitch 及相关用法，请百度或谷歌关键字：usb modeswitch 。

在 2023年6月6日星期二，Amuro Ray ***@***.***> 写道：
