### ISSUE TITLE
请问一下，如何手动升级玩客云的内核版本？

### ISSUE THREAD

**Issue by hkbase** [hzyitc/armbian-onecloud#28]
哪位大神知道具体操作？？ 烦请指教一下，谢谢

**Comment by hzyitc** [comment]
Armbian编译成功后，会在`output/debs/`下面生成相关的`deb包`，安装即可。

不过我至今也没有对`kernel`版本进行过较大的升级。

**Comment by hkbase** [comment]
能否把对应的deb包同固件一并发布releases里呢？

**Comment by hzyitc** [comment]
deb包名字均相同，需要改名才能上传。之后会做的，目前暂时在忙别的。

需要deb包的话，可以去action那边下载。

**Comment by hkbase** [comment]
收到了，感谢大神🙏，祝您一切顺利

**Comment by hzyitc** [comment]
add in commit e5abc308

**Comment by Continueder** [comment]
感谢
