### ISSUE TITLE
请问直刷包新版出来后怎么在不刷机的情况下更新?

### ISSUE THREAD

**Issue by gfourdx** [hzyitc/armbian-onecloud#34]
如题, 请教一下大佬, 强迫症看见新版本就想刷, 但是每次刷完又得重新配置, 有没有不重刷就可以更新的办法呢?

**Comment by gfourdx** [comment]
还有就是刷完8月18号的版本后, 启动时间明显变长, 迟迟无法用ssh登录, 对比15号的版本, 慢了3-5分钟呢

**Comment by hzyitc** [comment]
kernel升级参考 #28 。

其他东西的话不好说。有些修改是直接把对应文件复制进去就行。

**Comment by gfourdx** [comment]
> kernel升级参考 #28 。

尴尬的发现, 当我打开 https://github.com/hzyitc/armbian-onecloud/actions/runs/2884320285 后不知道怎么下载deb包
