### ISSUE TITLE
hdmi不输出启动信息和终端登录界面

### ISSUE THREAD

**Issue by maxmib** [hzyitc/armbian-onecloud#36]
玩客云版本 v1.0,刷入8月20日的Armbian_22.08.0-trunk_Onecloud_bullseye_current_5.15.61.burn.img后，开机界面停留在uboot界面的boot from emmc，实际接入网线后可以正常获得ip地址ssh登录。

**Comment by hzyitc** [comment]
目前仅 `edge` 支持 `HDMI` 。

`current` 暂不支持 `HDMI` 。之后会考虑对其添加 `HDMI` 支持。
