### ISSUE TITLE
5.18 rc7启动比rc3慢很多

### ISSUE THREAD

**Issue by shiyu1314** [hzyitc/armbian-onecloud#37]

**Comment by gfourdx** [comment]
一样的问题, 1.0的板子, 从18号编译的那版开始就发现这个问题了

**Comment by hkbase** [comment]
是因为ssh服务老是挂掉，所以给人造成的感觉是启动慢，其实系统早就ready了，是ssh服务没有ready。

**Comment by hzyitc** [comment]
应该是仅第一次启动慢而已吧。

大概率是引入 [armbian/build#3774](https://github.com/armbian/build/pull/3774) 导致的。但去掉这个 patch 会导致 #21 的问题。

**Comment by gfourdx** [comment]
> 应该是仅第一次启动慢而已吧。
> 
> 大概率是引入 [patch 3774](https://github.com/armbian/build/pull/3774) 导致的。但去掉这个 patch 会导致 #21 的问题。

我1.0板子, bullseye edge minimal, 每次插拔电源开机, 都很慢

**Comment by hkbase** [comment]
我刚测试过，在最新的版本中已经解决了，2022-08-24 14:41:51 UTC(+00:00)

**Comment by hzyitc** [comment]
上游patch已更新
