### ISSUE TITLE
请问macos应该如何连接玩客云?

### ISSUE THREAD

**Issue by gfourdx** [hzyitc/armbian-onecloud#38]
当我从windows转移到mac时, 对比windows, 我发现捅屁股的方式, windows可以识别, mac无法识别, 请问该如何连接?

**Comment by hzyitc** [comment]
macOS下也没有刷机工具吧

**Comment by gfourdx** [comment]
> 

我安装了虚拟机, 虚拟机里安装刷机工具, 驱动也能安装上
目前就是没办法识别设备...
