### ISSUE TITLE
sshd服务会自动死掉

### ISSUE THREAD

**Issue by hkbase** [hzyitc/armbian-onecloud#39]
最新的固件刷入机器后，需要等待很长时间，ssh才能偶尔连接成功。

**Comment by gfourdx** [comment]
一样的问题, 1.0的板子, 从18号编译的那版开始就发现这个问题了

**Comment by hkbase** [comment]
感觉这个ssh服务在不断的挂掉-重启-挂掉-重启。。。

**Comment by hkbase** [comment]
![image](https://user-images.githubusercontent.com/9875710/186085241-e6e89e1a-11d8-4ddc-ac38-488c40aa03e5.png)

**Comment by gfourdx** [comment]
> 感觉这个ssh服务在不断的挂掉-重启-挂掉-重启。。。

我到没有, 就是慢
通电启动后, HDMI输出的信息中显示要很久才能登录
但在这之前终端里已经可以用ssh登录了, 只不过相比之前的版本还是慢

**Comment by hzyitc** [comment]
```
systemctl status sshd
```

看下sshd具体状态。

**Comment by hzyitc** [comment]
与 #37 相同问题
