### ISSUE TITLE
感谢大佬的辛苦付出，顶礼膜拜。

### ISSUE THREAD

**Issue by stonegitt** [hzyitc/armbian-onecloud#44]
大佬可不可以分享一下晶晨做线刷包的方法，自己配置好的系统想做成线刷包。

**Comment by MDCY9008** [comment]
你可以先参考一下```workflow```
https://github.com/hzyitc/armbian-onecloud/blob/readme/.github/workflows/ci.yml
打包工具也是大佬做的 https://github.com/hzyitc/AmlImg

**Comment by hzyitc** [comment]
`commands.txt`中分区名需要根据u-boot的分区表进行修改。请注意，u-boot的分区表与MBR中的分区表并不相同。u-boot分区表硬编码在u-boot中的，无法修改。刷写命令仅使用内部分区表来定位。

**Comment by stonegitt** [comment]
> `commands.txt`中分区名需要根据u-boot的分区表进行修改。请注意，u-boot的分区表与MBR中的分区表并不相同。u-boot分区表硬编码在u-boot中的，无法修改。刷写命令仅使用内部分区表来定位。
感谢大佬指点。
