### ISSUE TITLE
WiFi那个44脚的空焊盘可以自定义吗，想引出一路UART来用

### ISSUE THREAD

**Issue by stonegitt** [hzyitc/armbian-onecloud#45]
在官方库里没有找到【patch/kernel/archive/meson-{5.10,5.18}/support-xunlei-onecloud.patch】这个内核补丁。

**Comment by stonegitt** [comment]
> 

感谢大佬，顺便问一下怎么取消系统分区校验呢，要不然经常卡98%

**Comment by mbskykill** [comment]
> > 
> 
> 感谢大佬，顺便问一下怎么取消系统分区校验呢，要不然经常卡98%

要修改线刷包里面的command.txt
