### ISSUE TITLE
直刷以后，启动一切正常，但是重启以后就只有22端口可以通过，其他端口都不可用了。

### ISSUE THREAD

**Issue by Bet5521** [hzyitc/armbian-onecloud#46]
如题，刷机以后，安装docker、青龙面板都是正常的，但是重启以后之前可用的端口都不再可用。重刷以后表现一致，开始都好用，重启就不行了。

**Comment by hzyitc** [comment]
请确保docker已运行，相关容器已启动

**Comment by Bet5521** [comment]
> 请确保docker已运行，相关容器已启动

SSH登录盒子，然后在里边可以看到docker已启动，青龙面板等容器也已经正常启动。但是对应的端口在局域网内是不能访问进去的，通过telnet 指定端口报连接失败。用nmap扫描，发现之前已开通的端口都不可用。重装docker拉取镜像，重新做了也不可访问。docker内日志正常。

**Comment by hzyitc** [comment]
用`lsof -i`看看监听是否正常。

**Comment by zy200813** [comment]
刷了包后，玩客云刚开始正常，运营1~2天后就ssh就登录不上了，有碰到过么？

**Comment by Bet5521** [comment]
> 用`lsof -i`看看监听是否正常。
已经刷机换了新版本固件，因此并未验证该问题。
原来刷的是Armbian_22.08.0-trunk_Onecloud_bullseye_edge_5.18.0.burn，尝试多次发现有这个问题，但并未lsof -i验证监听是否正常。
最近刷了Armbian_22.11.0-trunk_Onecloud_bullseye_edge_5.18.19.burn以后，该现象消失了，但是又发现了两个新问题。
问题1、使用armbian-config 安装omv，成功以后重启设备后无法进入系统，接显示器出现U-BOOT页面，一直循环重启无法进入系统，使用omv的安装命令安装也是会重启以后无法进入系统，但是并未插显示器，不确定是不是卡u-boot。
问题2、在一台1.0版本的玩客云设备刷这个固件以后，发现没有SD卡驱动器，插卡无反应。
root@CasaOS:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            460M     0  460M   0% /dev
tmpfs           100M  4.5M   95M   5% /run
/dev/mmcblk1p2  6.7G  2.4G  4.3G  36% /
tmpfs           497M     0  497M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           497M  8.0K  497M   1% /tmp
/dev/mmcblk1p1  200M   63M  138M  32% /boot
/dev/zram1       49M  2.7M   43M   6% /var/log
overlay         6.7G  2.4G  4.3G  36% /var/lib/docker/overlay2/ac1b2ffbbfa6deaeed4d161f834c7bc339ecfac58ea1a6e168365fc663317942/merged
tmpfs           100M     0  100M   0% /run/user/0
在/dev/路径下只有mmcblk1 驱动器，没有mmcblk0驱动器。

**Comment by hzyitc** [comment]
前者 #14 提了。

后者建议检查下卡槽。
