### ISSUE TITLE
FEEDBACK: is the USB closed to the HDMI working?

### ISSUE THREAD

**Issue by hzyitc** [hzyitc/armbian-onecloud#5]
I'm trying to fix the `USB` closed to the `HDMI` in [branch usb](https://github.com/hzyitc/armbian-onecloud/tree/usb).

我正在在[usb分支](https://github.com/hzyitc/armbian-onecloud/tree/usb)尝试修复靠近`HDMI`的`USB`。

Please try [test-usb-ci-20220603-2028](https://github.com/hzyitc/armbian-onecloud/releases/tag/test-usb-ci-20220603-2028) and [test-usb-ci-20220603-2029](https://github.com/hzyitc/armbian-onecloud/releases/tag/test-usb-ci-20220603-2029) to check whether `USB` closed to the `HDMI` working.

请使用[test-usb-ci-20220603-2028](https://github.com/hzyitc/armbian-onecloud/releases/tag/test-usb-ci-20220603-2028)和[test-usb-ci-20220603-2029](https://github.com/hzyitc/armbian-onecloud/releases/tag/test-usb-ci-20220603-2029)，测试靠近`HDMI`的`USB`能否正常使用。

For `V1.0 board`, ***both of them*** should work.

对于`V1.0的板子`，***这两者*** 应该都能正常工作。

For `V1.3 board`, ***only the second one*** should work.

对于`V1.3的板子`，应该 ***只有后者*** 能正常工作。

Please the following template to reply.

请使用下列模板回复。

# Template
```
Board: V1.3
test-usb-ci-20220603-2028: ❌
test-usb-ci-20220603-2029: ✔️
```

**Comment by hzyitc** [comment]
Board: V1.3
test-usb-ci-20220603-2028: ❌
test-usb-ci-20220603-2029: ✔️

**Comment by hzyitc** [comment]
Board: V1.0
test-usb-ci-20220603-2028: ✔️
test-usb-ci-20220603-2029: ✔️

**Comment by soulant** [comment]
Board: V1.3
test-usb-ci-20220603-2028: no test
test-usb-ci-20220603-2029: ✔️

**Comment by MDCY9008** [comment]
Board: V1.0
test-usb-ci-20220603-2028: ✔️
test-usb-ci-20220603-2029: ✔️

**Comment by Mirrorlife** [comment]
Board: V1.0
test-usb-ci-20220603-2028: ✔️
test-usb-ci-20220603-2029: ✔️

**Comment by TheOnlySakura** [comment]
Board: V1.0
test-usb-ci-20220603-2028: ✔️
test-usb-ci-20220603-2029: ✔️

**Comment by indiboy** [comment]
下载了镜像，测试靠近HDMI的USB能否正常使用？

**Comment by moranrabbit** [comment]
Board: V1.3
test-usb-ci-20220603-2028: ❌
test-usb-ci-20220603-2029: ✔️

**Comment by hzyitc** [comment]
Finished. Close.
