### ISSUE TITLE
重启设备之后，无法找到设备

### ISSUE THREAD

**Issue by GayFirends** [hzyitc/armbian-onecloud#51]
由于手头上并没有TTL所以暂时不知道是什么问题，只能简略的说一下发现过程。
第一次，是在docker等服务运行正常近半个月之后，把外挂USB硬盘添加了开机自动挂载后重启测试发现无法启动，怀疑是fstab文件书写错误。于是重刷。
第二次，开机后未添加fstab文件，未安装docker。仅通过armbian-config安装OMV后自动重启后，发现仍无法启动。
这期间ping主机名onecloud都无法ping通，此外路由器后台也没有什么新设备上线的提示，所以判断系统没有正常启动成功，但是网线口的灯都是亮的，而且设备貌似会不定时重启，网线口的灯会灭一段时间后再次亮起。

由于没有TTL设备，没有办法提供日志文件，在此表示歉意。

**Comment by weigeloveu** [comment]
这个真没有遇到类似的情况，目前刷了三台设备都很稳定，都是debian edge minimal，之前有一台是legacy不太稳定跑docker有时候死机，刷成edge后就好了。开始你说的症状我也感觉是fstab问题，可以接显示屏或者电视看看代码输出

**Comment by trytrytogo** [comment]
测试了3个，情况情况差不多。
Armbian_22.11.0-trunk_Onecloud_jammy_legacy_5.10.149.burn.img
Armbian_22.11.0-trunk_Onecloud_bullseye_edge_6.0.3.burn.img
Armbian_22.11.0-trunk_Onecloud_jammy_edge_6.0.3.burn.img

我可能和楼主有点区别。

我也是写的fstab。 测试情况是硬盘没挂载上的情况（环境：机器挂载硬盘正常→关机→人为拔掉挂载的硬盘→开机，开机失败）。
原来已经设置为蓝灯了，现在开启一直处于红灯，网卡灯常亮，无法获取IP。
由于没显示器，所以暂时也看不到具体的报错内容。

不知道楼主解决了这个问题没

**Comment by hzyitc** [comment]
fstab挂载失败会导致系统启动失败，进入紧急模式。Linux就是这样。可以考虑使用systemd的automount来避免这个问题。

**Comment by hzyitc** [comment]
omv见 #14
