### ISSUE TITLE
最新9.21版本docker无法启动。

### ISSUE THREAD

**Issue by yulinsoft** [hzyitc/armbian-onecloud#54]
最新9.21版本docker无法启动。删掉的9.18版本也无法启动docker。现在用9.14版可以正常启动docker。

**Comment by BH9FXK** [comment]
docker和iptables不兼容
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
sudo systemctl restart docker.service

**Comment by hzyitc** [comment]
请贴错误日志。

我这边能正常启动docker。

**Comment by yulinsoft** [comment]
我用的是流量宝盒，S805、512M内存，修改了dtb和启动脚本。9.14版本可以正常启动docker。9.18和9.21版本不知有什么改动，其它都正常，就是docker启动不了，当时也看了日志，没提示什么具体错误。既然玩客云正常，请关闭这个反馈。

**Comment by yulinsoft** [comment]
我用的是流量宝盒，S805、512M内存，修改了dtb和启动脚本。9.14版本可以正常启动docker。9.18和9.21版本不知有什么改动，其它都正常，就是docker启动不了，当时也看了日志，没提示什么具体错误。既然玩客云正常，请关闭这个反馈。

**Comment by Yellow-Fitz** [comment]
> 我用的是流量宝盒，S805、512M内存，修改了dtb和启动脚本，用的是jammy_current版本。9.14版本可以正常启动docker。9.18和9.21版本不知有什么改动，其它都正常，就是docker启动不了，当时也看了日志，没提示什么具体错误。既然玩客云正常，请关闭这个反馈。

您好，能分享一下流量宝盒的固件嘛？我想拿来跑跑docker？谢谢

**Comment by FrankLiangCN** [comment]
docker无法启动的日志

root@onecloud:~# systemctl status docker.service
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-09-30 17:54:13 CST; 13s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 16957 ExecStart=/usr/sbin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock $DOCKER_OPTS (code=exited, status=1/FAILURE)
   Main PID: 16957 (code=exited, status=1/FAILURE)
        CPU: 399ms

Sep 30 17:54:13 onecloud systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Sep 30 17:54:13 onecloud systemd[1]: Stopped Docker Application Container Engine.
Sep 30 17:54:13 onecloud systemd[1]: docker.service: Start request repeated too quickly.
Sep 30 17:54:13 onecloud systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 30 17:54:13 onecloud systemd[1]: Failed to start Docker Application Container Engine.
root@onecloud:~# sudo systemctl disable firewall
Failed to disable unit: Unit file firewall.service does not exist.
root@onecloud:~# systemctl daemon-reload
root@onecloud:~# service docker start
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by hzyitc** [comment]
在`journalctl -xe`里面找一下docker相关的log。

如果还是没有的话，手动跑一下`/usr/sbin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock $DOCKER_OPTS`，看看提示什么错误。

**Comment by ahhbsz** [comment]
> 最新9.21版本docker无法启动。删掉的9.18版本也无法启动docker。现在用9.14版可以正常启动docker。

你好，请问流量宝盒怎么刷入？

**Comment by ahhbsz** [comment]
> > 我用的是流量宝盒，S805、512M内存，修改了dtb和启动脚本，用的是jammy_current版本。9.14版本可以正常启动docker。9.18和9.21版本不知有什么改动，其它都正常，就是docker启动不了，当时也看了日志，没提示什么具体错误。既然玩客云正常，请关闭这个反馈。
> 
> 您好，能分享一下流量宝盒的固件嘛？我想拿来跑跑docker？谢谢

请问你的流量宝盒刷成功了吗？

**Comment by yulinsoft** [comment]
成功了，可以docker青龙。
![Screenshot_2022-10-05-13-59-27-742_com sonelli juicessh](https://user-images.githubusercontent.com/25970770/193992024-17a86429-2133-46ee-b46f-d97686dcac41.jpg)

**Comment by Yellow-Fitz** [comment]
> 成功了，可以docker青龙。 ![Screenshot_2022-10-05-13-59-27-742_com sonelli juicessh](https://user-images.githubusercontent.com/25970770/193992024-17a86429-2133-46ee-b46f-d97686dcac41.jpg)

可以分享一下固件或者教一下如何修改dtb这些嘛？谢谢

**Comment by ahhbsz** [comment]
>刷的哪个？有简单的步骤吗？

**Comment by yulinsoft** [comment]
恩山有线刷包，我用的是自己改的，还在测试中。

**Comment by ahhbsz** [comment]
> 

谢谢。希望测好能分享下。

**Comment by Shiraha-cloud** [comment]
> docker无法启动的日志
> 
> root@onecloud:~# systemctl status docker.service ● docker.service - Docker Application Container Engine Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Fri 2022-09-30 17:54:13 CST; 13s ago TriggeredBy: ● docker.socket Docs: https://docs.docker.com Process: 16957 ExecStart=/usr/sbin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock $DOCKER_OPTS (code=exited, status=1/FAILURE) Main PID: 16957 (code=exited, status=1/FAILURE) CPU: 399ms
> 
> Sep 30 17:54:13 onecloud systemd[1]: docker.service: Scheduled restart job, restart counter is at 3. Sep 30 17:54:13 onecloud systemd[1]: Stopped Docker Application Container Engine. Sep 30 17:54:13 onecloud systemd[1]: docker.service: Start request repeated too quickly. Sep 30 17:54:13 onecloud systemd[1]: docker.service: Failed with result 'exit-code'. Sep 30 17:54:13 onecloud systemd[1]: Failed to start Docker Application Container Engine. root@onecloud:~# service docker start Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

我和你一样的问题，错误代码也一样，请问现在解决了吗

**Comment by liquehuo** [comment]
我也是这样 ，怎么弄 大哥们 ？ 直刷的最新的包   22  11 18

**Comment by ahhbsz** [comment]
我也不会啊啊啊，求教程


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月29日(星期二) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hzyitc/armbian-onecloud] 最新9.21版本docker无法启动。 (Issue #54)




 
我也是这样 ，怎么弄 大哥们 ？ 直刷的最新的包   22  11 18

**Comment by ag598** [comment]
各位大侠，怎么解决docker无法启动的问题？

**Comment by hzyitc** [comment]
https://github.com/armbian/build/issues/4264#issuecomment-1271129353
