### ISSUE TITLE
请问能给适配个赚钱宝Pro的固件吗？

### ISSUE THREAD

**Issue by hixiaolu** [hzyitc/armbian-onecloud#56]
玩客云的二代机器ws1508，用大佬你的包也可以刷，但是好像uboot不对，还是启动不了，大佬要是有时间有兴趣麻烦辛苦给大家伙适配下。

**Comment by hzyitc** [comment]
手头没有相关硬件，无法测试。抱歉

**Comment by Yellow-Fitz** [comment]
> 

大佬，要不我寄两个给你试一下？
