### ISSUE TITLE
可以附带搞个T1的armbian吗？

### ISSUE THREAD

**Issue by heham** [hzyitc/armbian-onecloud#58]
S912比老母鸡的805还是要强点的，现在T1的armbian都不完善版本也老

**Comment by MDCY9008** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian

**Comment by hzyitc** [comment]
这类CPU都是arm64的，跟S805还是有很大区别的。

个人没有硬件，无法提供支持。

且`Armbian`有团队在负责维护`meson64`。`khadas-vim2`就是S912的板子。
