### ISSUE TITLE
收集下`eMMC`大小，考虑更换`f2fs`文件系统。

### ISSUE THREAD

**Issue by hzyitc** [hzyitc/armbian-onecloud#59]
近期在考虑是否要将 `rootfs` 更换成 `f2fs` 文件系统。`f2fs` 理论上拥有更好的随机性能。但 `f2fs` 无法在线扩容，故在编译时需要指定大小。现收集下各位的 `eMMC` 大小，看是否有可行性。

请使用一下模板回复：

    板子：V1.0/V1.3
    fdisk:
    ```
    `fdisk -l /dev/mmcblk1` 的输出结果
    ```
    lsblk:
    ```
    `lsblk --bytes /dev/mmcblk1` 的输出结果
    ```

**Comment by hzyitc** [comment]
板子：V1.0
fdisk:
```
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux
```
lsblk:
```
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINTS
mmcblk1     179:0    0 7818182656  0 disk
tqmmcblk1p1 179:1    0  268435456  0 part /boot
mqmmcblk1p2 179:2    0 7361003520  0 part /var/log.hdd
                                          /
```

**Comment by quidlaw** [comment]
resize.f2fs在buster下是可以使用的，bullseye的版本是有问题的，我是通过usb启动U盘执行的。

**Comment by weigeloveu** [comment]
之前刷了3台，忘了是哪个版本的板子了，印象中是两个板子都有，放在远程，没法拆机验证版本了。不过数据跟你这边是一样的。
fdisk:
```
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux 
```
lsblk:
```
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk 
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7361003520  0 part / 
```

**Comment by yunkaig** [comment]
板子: V1.0
fdisk:
```
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux
```
lsblk:
```
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
mmcblk1      179:0    0   7.3G  0 disk 
├─mmcblk1p1  179:1    0   256M  0 part /boot
└─mmcblk1p2  179:2    0   6.9G  0 part /
mmcblk1boot0 179:16   0     4M  1 disk 
mmcblk1boot1 179:32   0     4M  1 disk 
zram0        253:0    0 495.3M  0 disk [SWAP]
zram1        253:1    0    50M  0 disk /var/log
```

**Comment by hzyitc** [comment]
> resize.f2fs在buster下是可以使用的，bullseye的版本是有问题的，我是通过usb启动U盘执行的。

主要是不能在线扩容。故无法做到系统自动扩容。

**Comment by jswxll** [comment]
U盘系统下fdisk对emmc分区，dd命令写入emmc，并扩展2分区size
板子: V1.0

fdisk：
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc88f7c58

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1        2048   411647   409600  200M  e W95 FAT16 (LBA)
/dev/mmcblk1p2      411648 15269887 14858240  7.1G 83 Linux

lsblk：
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk
├─mmcblk1p1 179:1    0  209715200  0 part /boot
└─mmcblk1p2 179:2    0 7607418880  0 part /

**Comment by mxjafe70245** [comment]
板子：V1.3
fdisk:
`Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc51a68de

Device         Boot   Start      End  Sectors  Size Id Type
/dev/mmcblk1p1       210944  1210367   999424  488M  c W95 FAT32 (LBA)
/dev/mmcblk1p2      1413120 15269887 13856768  6.6G 83 Linux`
lsblk:
`NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk
├─mmcblk1p1 179:1    0  511705088  0 part /boot
└─mmcblk1p2 179:2    0 7094665216  0 part /`

**Comment by GaoQianNew** [comment]
板子：V1.0

fdisk: fdisk -l /dev/mmcblk1

Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00002ceb
Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *     32768   557055   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    557056 15269887 14712832    7G 83 Linux

lsblk: lsblk --bytes /dev/mmcblk1

NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk 
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7532969984  0 part /

**Comment by quidlaw** [comment]
> > resize.f2fs在buster下是可以使用的，bullseye的版本是有问题的，我是通过usb启动U盘执行的。
> 
> 主要是不能在线扩容。故无法做到系统自动扩容。

既然要通过U盘写入到emmc，相比固定空间，是不是通过脚本在写入后执行resize.f2fs（可以正确工作的版本）也可以？btw我的是7.28GiB。

**Comment by hzyitc** [comment]
> 既然要通过U盘写入到emmc

只打算修改直刷包。

> 脚本在写入后执行resize.f2fs

通过脚本的话，在建文件系统的时候就已经扩到分区大小了。

**Comment by quidlaw** [comment]
> > 既然要通过U盘写入到emmc
> 
> 只打算修改直刷包。
> 
> > 脚本在写入后执行resize.f2fs
> 
> 通过脚本的话，在建文件系统的时候就已经扩到分区大小了。

了解了，我和他们的闪存是一样的，但是板子不知道是哪个版本，没拆过机器。可以请教下如何更新uboot吗？

**Comment by hzyitc** [comment]
> 可以请教下如何更新uboot吗？

见 hzyitc/u-boot-onecloud#2

当然你也可以用 `USB Burning Tools` 直接把 [eMMC.burn.img](https://github.com/hzyitc/u-boot-onecloud/releases/latest/download/eMMC.burn.img) 刷进去

**Comment by H2295** [comment]
板子：1.3
fdisk
fdisk -l /dev/mmcblk1
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6
Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux


lsblk --bytes /dev/mmcblk1
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk 
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7361003520  0 part /

**Comment by kuoruan** [comment]
板子：1.0

```
# fdisk -l /dev/mmcblk1
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux
root@onecloud:~# lsblk --bytes /dev/mmcblk1
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7361003520  0 part /
```

**Comment by hkbase** [comment]
玩客云主板：v1.3

# fdisk -l /dev/mmcblk1
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux

# lsblk --bytes /dev/mmcblk1
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:16   0 7818182656  0 disk 
├─mmcblk1p1 179:17   0  268435456  0 part /boot
└─mmcblk1p2 179:18   0 7361003520  0 part /

**Comment by hkbase** [comment]
使用最新带burn的镜像烧入固件后，进入ssh查看分区情况，发现有未利用的空间（171M+8M），老大能否优化一下默认分区，把所有空间都利用起来呢？
见下面：
# cfdisk /dev/mmcblk1
![image](https://user-images.githubusercontent.com/9875710/197497513-f6b065ad-69fe-4486-ad59-da40209645d5.png)

**Comment by lanlanpy** [comment]
> 使用最新带burn的镜像烧入固件后，进入ssh查看分区情况，发现有未利用的空间（171M+8M），老大能否优化一下默认分区，把所有空间都利用起来呢？
> 见下面：
> # cfdisk /dev/mmcblk1
> ![image](https://user-images.githubusercontent.com/9875710/197497513-f6b065ad-69fe-4486-ad59-da40209645d5.png)
> 

8是uboot和env存放地址，100多那个好像是存在启动logo图片那些的

**Comment by hzyitc** [comment]
> 使用最新带burn的镜像烧入固件后，进入ssh查看分区情况，发现有未利用的空间（171M+8M），老大能否优化一下默认分区，把所有空间都利用起来呢？

最新版的u-boot已调整。

**Comment by lolion1y** [comment]
板子：V1.0
fdisk:
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00002ceb

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *     32768   557055   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    557056 15269887 14712832    7G 83 Linux

lsblk:
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk 
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7532969984  0 part /

**Comment by Cp0204** [comment]
板子：V1.3
fdisk:
```
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf263d909

Device         Boot   Start      End  Sectors  Size Id Type
/dev/mmcblk1p1       210944  1210367   999424  488M  c W95 FAT32 (LBA)
/dev/mmcblk1p2      1413120 15269887 13856768  6.6G 83 Linux
```
lsblk:
```
onecloud:~:# lsblk --bytes /dev/mmcblk1
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk
├─mmcblk1p1 179:1    0  511705088  0 part /boot
└─mmcblk1p2 179:2    0 7094665216  0 part /
```

**Comment by Bet5521** [comment]
V1.3
fdisk
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6
Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux
lsklk
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:16   0 7818182656  0 disk 
├─mmcblk1p1 179:17   0  268435456  0 part /boot
└─mmcblk1p2 179:18   0 7361003520  0 part /
V1.0
fdisk
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000048c6
Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk1p1 *    352256   876543   524288  256M  e W95 FAT16 (LBA)
/dev/mmcblk1p2 *    892928 15269887 14376960  6.9G 83 Linux
lsblk
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk 
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7361003520  0 part /

**Comment by xiaoxia625** [comment]
V1.3
fdisk
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00002ceb
Device         Boot  Start      End  Sectors Id Type            Start-C/H/S   End-C/H/S Attrs
/dev/mmcblk1p1 *     32768   557055   524288  e W95 FAT16 (LBA) 1023/254/63 1023/254/63    80
/dev/mmcblk1p2 *    557056 15269887 14712832 83 Linux           1023/254/63 1023/254/63    80

lsblk
NAME        MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 7818182656  0 disk 
├─mmcblk1p1 179:1    0  268435456  0 part /boot
└─mmcblk1p2 179:2    0 7532969984  0 part /

**Comment by ShallowAi** [comment]
板子：V1.0
fdisk:
```
Disk /dev/mmcblk1: 7.28 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00002ceb
Device Boot Start End Sectors Id Type
/dev/mmcblk1p1 * 32768 557055 524288 e W95 FAT16 (LBA)
/dev/mmcblk1p2 * 557056 15269887 14712832 7G 83 Linux
```
lsblk:
```
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
mmcblk1 179:0 0 7818182656 0 disk
├─mmcblk1p1 179:1 0 268435456 0 part /boot
└─mmcblk1p2 179:2 0 7532969984 0 part /
```
