### ISSUE TITLE
直刷安装docker重启后系统一直异常不恢复

### ISSUE THREAD

**Issue by XXIN0** [hzyitc/armbian-onecloud#61]
硬件：V1.3
软件烧录：Armbian_22.11.0-trunk_Onecloud_bullseye_edge_5.19.16.burn.img
内存卡格式：ext4
系统安装后主要做了以下操作：

1  安装ttyd，重启可正常工作。

2  安装samba，并挂载硬盘分享，重启可正常工作。

3  安装docker
  3.1  然后安装portainer、transmission，配置相关参数后，重启系统，系统异常无法正常启动
	_ps:配置docker，将tfcard/docker 软连接系统var/lib/docker （tfcard为挂载的存储卡）_
	
        **现象如下**
		3.1.1  无法挂载sdcard
		3.1.2  网卡无法正常工作，ssh失效
		3.1.3  连接hdmi可正常工作，连接显示器系统还能正常运行,接上键盘还能操作，但是很多服务应该不工作了

出现问题后重启也不恢复，一直处于不恢复的状态。

附件为连接串口抓取的日志。
[log.zip](https://github.com/hzyitc/armbian-onecloud/files/9841393/log.zip)

**Comment by XXIN0** [comment]
今天通过ttl先把docker卸载了，再重装，再reboot，系统没有挂::>_<::

**Comment by lanlanpy** [comment]
感觉是你软链docker数据储存目录的原因，还有你的内存卡文件系统格式是什么，如果不是ext4的不行.
修改docker数据目录，20以后的版本可以修改 /etc/docker/daemon.json 文件 具体看教程，https://zhuanlan.zhihu.com/p/469997046
修改之前做好内存卡启动挂载，最好别在fstab写挂载参数，有时候内存卡出问题了，挂载不上，系统好像会启动不了。
把挂载命令加入etc/rc.local ，或者写个挂载shell脚本 ，加入到开机启动

**Comment by XXIN0** [comment]
> 

内存卡文件系统是ext4的，好的我研究下怎么把挂载命令加入etc/rc.local,谢谢。

**Comment by XXIN0** [comment]
> 感觉是你软链docker数据储存目录的原因，还有你的内存卡文件系统格式是什么，如果不是ext4的不行. 修改docker数据目录，20以后的版本可以修改 /etc/docker/daemon.json 文件 具体看教程，https://zhuanlan.zhihu.com/p/469997046 修改之前做好内存卡启动挂载，最好别在fstab写挂载参数，有时候内存卡出问题了，挂载不上，系统好像会启动不了。 把挂载命令加入etc/rc.local ，或者写个挂载shell脚本 ，加入到开机启动

内存卡文件系统是ext4的，好的我研究下怎么把挂载命令加入etc/rc.local,谢谢。

**Comment by lanlanpy** [comment]
> > 感觉是你软链docker数据储存目录的原因，还有你的内存卡文件系统格式是什么，如果不是ext4的不行. 修改docker数据目录，20以后的版本可以修改 /etc/docker/daemon.json 文件 具体看教程，https://zhuanlan.zhihu.com/p/469997046 修改之前做好内存卡启动挂载，最好别在fstab写挂载参数，有时候内存卡出问题了，挂载不上，系统好像会启动不了。 把挂载命令加入etc/rc.local ，或者写个挂载shell脚本 ，加入到开机启动
> 
> 内存卡文件系统是ext4的，好的我研究下怎么把挂载命令加入etc/rc.local,谢谢。

因为已经分好区，格式化好了，所以，只需要在rc.local加入mount 内存卡到指定路径就可以了。比如mount  /dev/mmcblk0p1  /mnt/docker

**Comment by hzyitc** [comment]
![image](https://user-images.githubusercontent.com/25414097/197511073-e4400248-3ec1-4339-b1a9-ffa43a178b3d.png)

log里面已经写明了故障原因了。
```
ext4: Unknown parameter 'defaults.nosuid'
```
逗号写成了句号

**Comment by XXIN0** [comment]
> > > 感觉是你软链docker数据储存目录的原因，还有你的内存卡文件系统格式是什么，如果不是ext4的不行. 修改docker数据目录，20以后的版本可以修改 /etc/docker/daemon.json 文件 具体看教程，https://zhuanlan.zhihu.com/p/469997046 修改之前做好内存卡启动挂载，最好别在fstab写挂载参数，有时候内存卡出问题了，挂载不上，系统好像会启动不了。 把挂载命令加入etc/rc.local ，或者写个挂载shell脚本 ，加入到开机启动
> > 
> > 
> > 内存卡文件系统是ext4的，好的我研究下怎么把挂载命令加入etc/rc.local,谢谢。
> 
> 因为已经分好区，格式化好了，所以，只需要在rc.local加入mount 内存卡到指定路径就可以了。比如mount /dev/mmcblk0p1 /mnt/docker

好的，谢谢。我找了automount的脚本，添加到开机脚本去了etc/init.d

**Comment by XXIN0** [comment]
> ![image](https://user-images.githubusercontent.com/25414097/197511073-e4400248-3ec1-4339-b1a9-ffa43a178b3d.png)
> 
> log里面已经写明了故障原因了。
> 
> ```
> ext4: Unknown parameter 'defaults.nosuid'
> ```
> 
> 逗号写成了句号

谢谢，后面用串口进去把docker关了也行了，目前没有问题了，然后我找了个automount的脚本加到开机脚本去了，目前暂时没有问题了，谢谢。
