### ISSUE TITLE
磁盘占用问题

### ISSUE THREAD

**Issue by XXIN0** [hzyitc/armbian-onecloud#65]
请问下我查看/dev/mmcblk1p2分区被用完了，但是实际du -sh /* | sort -nr确发现没有使用那么多，请问下该如何解决？
![image](https://user-images.githubusercontent.com/41498132/198811631-999e78ef-1a2c-4f6e-b4ee-75dfebfe5057.png)

**Comment by XXIN0** [comment]
尝试过lsof -n |  grep deleted，也没有发现占用的文件

**Comment by hzyitc** [comment]
检查`/`目录下有没有大文件吧

**Comment by XXIN0** [comment]
> 

没有找到大文件，隐藏文件也没有，折腾一天了，想重装系统了都::>_<::

**Comment by XXIN0** [comment]
> 检查`/`目录下有没有大文件吧

没有找到大文件，隐藏文件也没有，折腾一天了，想重装系统了都::>_<::

**Comment by hzyitc** [comment]
有一种情况，可能是有文件在`/mnt`下。你先把`/mnt`卸载了，然后看看里面有没有文件。

**Comment by XXIN0** [comment]
> 有一种情况，可能是有文件在`/mnt`下。你先把`/mnt`卸载了，然后看看里面有没有文件。

我去，还真有，这些没挂载咋也有呢
![image](https://user-images.githubusercontent.com/41498132/198824903-ae96739b-9aad-48ed-83f2-3def0ab9903e.png)

**Comment by XXIN0** [comment]
好迷茫。。能请告知下这个是怎么造成的呢

**Comment by hzyitc** [comment]
在没挂载之前写入了。

**Comment by XXIN0** [comment]
> 在没挂载之前写入了。

好的，十分感谢，那向这种情况怎么避免呢，已经加入开机脚本挂载了，还是会失败，sdcard挂载感觉不是很稳定，这种是不是无解。
