### ISSUE TITLE
该直刷包Armbian_22.11.0-trunk_Onecloud_bullseye_current_5.15.74.burn，samb问题

### ISSUE THREAD

**Issue by xiaoxia625** [hzyitc/armbian-onecloud#66]
我今天刷的这个直刷包，发现samb有问题。我按网上的教程，正确修改了配置文件，samb账号密码也正确设置了，但是通过手机和电脑访问共享IP时，总是提示账户密码错误，无法进入共享文件夹。

**Comment by hzyitc** [comment]
应该还是配置问题。

**Comment by xiaoxia625** [comment]
> 应该还是配置问题。
发现新问题如下： 如果设置samb访问账号的话，配置改为匿名访问，此时在局域网内也不能正常访问；但若删除建立的访问账号，之后就能访问了，感觉是samb账号建立的问题

**Comment by xiaoxia625** [comment]
该问题已解决，是配置问题。
