### ISSUE TITLE
直刷包Armbian_22.11.0-trunk_Onecloud_bullseye_current_5.15.74.burn，100M局域网内上下行速率差异较大

### ISSUE THREAD

**Issue by xiaoxia625** [hzyitc/armbian-onecloud#67]
C:\Users\root\Desktop\iperf-3.1.3-win64>iperf3 -c 192.168.31.153
Connecting to host 192.168.31.153, port 5201
[  4] local 192.168.31.53 port 61749 connected to 192.168.31.153 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec  9.50 MBytes  78.7 Mbits/sec
[  4]   1.01-2.00   sec  9.62 MBytes  81.8 Mbits/sec
[  4]   2.00-3.00   sec  10.0 MBytes  83.9 Mbits/sec
[  4]   3.00-4.00   sec  11.2 MBytes  94.4 Mbits/sec
[  4]   4.00-5.00   sec  11.4 MBytes  95.4 Mbits/sec
[  4]   5.00-6.00   sec  10.5 MBytes  88.1 Mbits/sec
[  4]   6.00-7.00   sec  11.4 MBytes  95.4 Mbits/sec
[  4]   7.00-8.00   sec  10.6 MBytes  89.1 Mbits/sec
[  4]   8.00-9.00   sec  11.2 MBytes  94.4 Mbits/sec
[  4]   9.00-10.00  sec  11.4 MBytes  95.4 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec   107 MBytes  89.6 Mbits/sec                  sender
[  4]   0.00-10.00  sec   107 MBytes  89.6 Mbits/sec                  receiver

iperf Done.

C:\Users\root\Desktop\iperf-3.1.3-win64>iperf3 -c 192.168.31.153 -R
Connecting to host 192.168.31.153, port 5201
Reverse mode, remote host 192.168.31.153 is sending
[  4] local 192.168.31.53 port 61771 connected to 192.168.31.153 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.07   sec  5.04 MBytes  39.5 Mbits/sec
[  4]   1.07-2.00   sec  2.94 MBytes  26.5 Mbits/sec
[  4]   2.00-3.00   sec  4.22 MBytes  35.4 Mbits/sec
[  4]   3.00-4.00   sec  1.55 MBytes  13.0 Mbits/sec
[  4]   4.00-5.00   sec  3.74 MBytes  31.4 Mbits/sec
[  4]   5.00-6.00   sec  5.53 MBytes  46.4 Mbits/sec
[  4]   6.00-7.00   sec  3.93 MBytes  32.9 Mbits/sec
[  4]   7.00-8.00   sec  3.57 MBytes  29.9 Mbits/sec
[  4]   8.00-9.00   sec  3.54 MBytes  29.7 Mbits/sec
[  4]   9.00-10.00  sec  5.23 MBytes  43.9 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  39.5 MBytes  33.1 Mbits/sec  771             sender
[  4]   0.00-10.00  sec  39.3 MBytes  33.0 Mbits/sec                  receiver

iperf Done.

**Comment by xiaoxia625** [comment]
root@onecloud:~# iperf3 -c 192.168.31.53 -F /dev/zero
Connecting to host 192.168.31.53, port 5201
[  5] local 192.168.31.153 port 59334 connected to 192.168.31.53 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  11.6 MBytes  97.5 Mbits/sec    9   74.9 KBytes       
[  5]   1.00-2.00   sec  9.57 MBytes  80.3 Mbits/sec    1    116 KBytes       
[  5]   2.00-3.00   sec  10.4 MBytes  87.6 Mbits/sec    8   79.2 KBytes       
[  5]   3.00-4.00   sec  11.4 MBytes  95.4 Mbits/sec    3   84.8 KBytes       
[  5]   4.00-5.00   sec  11.1 MBytes  92.8 Mbits/sec    5   77.8 KBytes       
[  5]   5.00-6.00   sec  11.2 MBytes  94.3 Mbits/sec    2    106 KBytes       
[  5]   6.00-7.00   sec  11.2 MBytes  93.8 Mbits/sec    2   94.7 KBytes       
[  5]   7.00-8.00   sec  10.9 MBytes  91.2 Mbits/sec    0    127 KBytes       
[  5]   8.00-9.00   sec  10.7 MBytes  89.7 Mbits/sec   10   65.0 KBytes       
[  5]   9.00-10.00  sec  11.2 MBytes  93.8 Mbits/sec    3   65.0 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   109 MBytes  91.6 Mbits/sec   43             sender
        Sent  109 MByte / 0.00 Byte (100%) of /dev/zero
[  5]   0.00-10.00  sec   109 MBytes  91.3 Mbits/sec                  receiver

iperf Done.

挺奇怪的，采用这种固定数据的方式测速就正常了。但实际在使用中内网访问速率只有4M左右，下载速率10M左右。

**Comment by xiaoxia625** [comment]
问题更新
玩客云网口只有靠近USB端口那个灯亮，颜色为黄色，另一个灯不亮。家里宽带是500M的，路由器是红米AC2100，千兆端口。另外，ssh显示玩客云网卡是全双工、1000M速率的。
root@onecloud:~# ethtool eth0
Settings for eth0:
        Supported ports: [ TP    MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  10baseT/Half 10baseT/Full
                                             100baseT/Half 100baseT/Full
                                             1000baseT/Full
        Link partner advertised pause frame use: Symmetric
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 1000Mb/s
        Duplex: Full
        Auto-negotiation: on
        master-slave cfg: preferred slave
        master-slave status: slave
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: external
        MDI-X: Unknown
        Supports Wake-on: ug
        Wake-on: d
        Current message level: 0x0000003f (63)
                               drv probe link timer ifdown ifup
        Link detected: yes

**Comment by hzyitc** [comment]
> 玩客云网口只有靠近USB端口那个灯亮，颜色为黄色，另一个灯不亮。

网卡灯无法反映什么。RTL8211默认配置下，LED灯知识与常规不一样。我没有添加调整LED的patch。

> 100M局域网内上下行速率差异较大 

速度问题 #2 提了，就不留多个issue了。
