### ISSUE TITLE
uboot下修改mac无效

### ISSUE THREAD

**Issue by Stone-Crown** [hzyitc/armbian-onecloud#70]
尝试修改mac，在interface里添加hwaddress ether 5a:55:3d:b0:b5:00 无效，在uboot下修改也无效，不知道mac怎么改，有知道的大佬告知一声，刷的edge mini

**Comment by jswxll** [comment]
我用nmtui修改，克隆mac一切正常

**Comment by Stone-Crown** [comment]
> 我用nmtui修改，克隆mac一切正常

按照的你的方法可以修改，谢谢！不过不知道是不是因为我修改了uboot里的mac，现在我发现我的eth0下有两个IPV6的地址。你也是两个IPV6么？

**Comment by Stone-Crown** [comment]
> 我用nmtui修改，克隆mac一切正常

而且这两个IPV6的地址似乎和mac都不能对应。
![image](https://user-images.githubusercontent.com/16874655/202619459-ced3bbe7-54b8-4f39-be2d-8eab0669f4da.png)

**Comment by jswxll** [comment]
> > 我用nmtui修改，克隆mac一切正常
> 
> 而且这两个IPV6的地址似乎和mac都不能对应。 ![image](https://user-images.githubusercontent.com/16874655/202619459-ced3bbe7-54b8-4f39-be2d-8eab0669f4da.png)

我这边的网络没有V6，所以直接禁用了~

**Comment by hzyitc** [comment]
ipv6获取的方法有两种：dhcp和slaac。

以及可能会有个保护隐私用的临时地址。

具体自行查找相关资料

**Comment by hzyitc** [comment]
目前版本的armbian不会去读取uboot变量。启动脚本也没传递mac。
