### ISSUE TITLE
20221118版装不了docker

### ISSUE THREAD

**Issue by hodrag** [hzyitc/armbian-onecloud#73]
1、apt update出错
2、安装docker失败

**Comment by hzyitc** [comment]
apt update出错，说明是网络相关的问题

**Comment by liquehuo** [comment]
大哥 你安装好docker没 ？ 我也安装不成功

**Comment by ihipop** [comment]
> 大哥 你安装好docker没 ？ 我也安装不成功

https://github.com/hzyitc/armbian-onecloud/issues/54#issuecomment-1257174989

执行那两个  update-alternative 然后重新安装即可
