### ISSUE TITLE
ddbr发生错误！

### ISSUE THREAD

**Issue by rmoyulong** [hzyitc/armbian-onecloud#74]
Using username "root".
  ___              ____ _                 _
 / _ \ _ __   ___ / ___| | ___  _   _  __| |
| | | | '_ \ / _ \ |   | |/ _ \| | | |/ _` |
| |_| | | | |  __/ |___| | (_) | |_| | (_| |
 \___/|_| |_|\___|\____|_|\___/ \__,_|\__,_|

Welcome to Armbian 22.11.0-trunk Jammy with Linux 6.0.9-meson

No end-user support: built from trunk

System load:   8%               Up time:       1 min
Memory usage:  7% of 990M       IP:            192.168.1.200
CPU temp:      45°C             Usage of /:    5% of 15G
storage/:      25% of 200M

[ Menu-driven system configuration (beta): sudo apt update && sudo apt install a                                                                                        rmbian-config ]

root@onecloud:~# cd /
root@onecloud:/# ls
bin  boot  ddbr  dev  etc  home  lib  lost+found  media  mnt  opt  proc  root  run  sbin  selinux  srv  sys  tmp  usr  var
root@onecloud:/# ddbr
 DO YOU WANT TO BACKUP OR RESTORE ?
 BACKUP=(b) RESTORE=(r) b
sed: -e expression #1, char 6: unterminated `s' command
 UNABLE TO FIND YOUR EMMC DRIVE OR YOU ALREADY RUN FROM EMMC!!!

**Comment by hzyitc** [comment]
这个是armbian上游的bug。最近我本人没空修。
