### ISSUE TITLE
硬盘休眠是否有解决办法？

### ISSUE THREAD

**Issue by dalaohu2025** [hzyitc/armbian-onecloud#78]
通过cd /dev/disk/by-id发现，硬盘已ata连接的是可以正常休眠的。如果是以USB连接的（我这里试过两个移动硬盘都是以USB方式连接的，ata连接的是易驱线连接）硬盘是无法正常休眠的，哪位高人看能否解决这个问题？

**Comment by hzyitc** [comment]
试试以下命令能不能休眠成功，如果可以的话，自己写个定时休眠脚本吧。

某些硬盘在我x86的NAS也是不能用定时休眠，但手动休眠是正常的。

```
hdparm -y /dev/sda
```
