### ISSUE TITLE
断电后，路由器就找不到玩客云了

### ISSUE THREAD

**Issue by dalaohu2025** [hzyitc/armbian-onecloud#79]
刷的最新版JAMMY，刚才断电重启后，路由器上就没玩客云了，路由器也重启好几次没用

**Comment by daLaohu200** [comment]
Armbian_23.02.0-trunk_Onecloud_jammy_edge_6.1.0.burn.img

**Comment by dalaohu2025** [comment]
找出问题了，本来是连接两块硬盘，我拔出一块，就连不上了。重新插上，就又可以登录了，貌似跟硬盘挂载又关系
