### ISSUE TITLE
感谢作者的幸苦付出，能否给镜像增加一个s805_autoscript启动脚本，启动脚本用的是ttl，新手去操作飞线或者焊线对动手能力要求还是很高的。

### ISSUE THREAD

**Issue by fvlw** [hzyitc/armbian-onecloud#8]
https://www.right.com.cn/forum/thread-8237343-1-1.html
这个帖子的作者写了个s805_autoscript在0.fat，可以使用这种方法打包镜像吗？

**Comment by hzyitc** [comment]
Duplicate #3

**Comment by MDCY9008** [comment]
> Duplicate #3

新的启动脚本无法启动，请问我这样添加是否正确。
![image](https://user-images.githubusercontent.com/54255527/172962811-139cd780-819c-489a-b2ce-6fdc26a2b8b2.png)
使用的是最新的```release``` ```snail```底包 ```1.0```的板子

**Comment by hzyitc** [comment]
目前并不支持自动启动

那些内容是在`u-boot`中运行

当然也可以写一个`s805_autoscript.cmd`存放这些内容，然后使用`mkimage -C none -A arm -T script -d s805_autoscript.cmd s805_autoscript.scr`编译出`s805_autoscript`，再放入`fat`中

**Comment by hzyitc** [comment]
之后会在本人自己的仓库中加入`s805_autoscript`的支持的

`s805_autoscript`以及`顺序尝试启动`并不符合`官方`的风格，故并没有打算并入`官方`

**Comment by hzyitc** [comment]
去 #3 讨论吧，重复问题就不多个`issue`讨论了
