### ISSUE TITLE
内核编译出错

### ISSUE THREAD

**Issue by MDCY9008** [hzyitc/armbian-onecloud#81]
![image](https://user-images.githubusercontent.com/54255527/215444613-91a3f263-c9a9-45fc-bec7-6efbeabcc841.png)

![image](https://user-images.githubusercontent.com/54255527/215447322-fa862d3e-d109-483a-aec0-a7a33c15389f.png)
legacy与edge分支均有此问题

**Comment by hzyitc** [comment]
https://github.com/hzyitc/armbian-onecloud/actions/runs/4043064824

legacy准备删了。

**Comment by hzyitc** [comment]
抱歉，edge确实也是patch失败。
