### ISSUE TITLE
无法安装docker问题

### ISSUE THREAD

**Issue by saenice** [hzyitc/armbian-onecloud#83]
尝试了许多版本；apt update 后安装apt install docker.io 都报错；【包含5.15&6.1&6.1.9】
![image](https://user-images.githubusercontent.com/56823170/217165209-7f57b65b-b416-4783-9b92-acf087df7522.png)

**Comment by saenice** [comment]
>6.1&6.1.9版本可以使用以下命令安装docker 
#apt update
#curl -fsSL https://get.docker.com -o get-docker.sh
#sh get-docker.sh --mirror=Aliyun

**Comment by hzyitc** [comment]
试试这个吧

https://github.com/hzyitc/armbian-onecloud/issues/54#issuecomment-1257174989
