### ISSUE TITLE
2月2号的版本无法识别U盘和移动硬盘

### ISSUE THREAD

**Issue by Rutenioum** [hzyitc/armbian-onecloud#84]
用的是这个镜像
`Armbian_23.02.0-trunk_Onecloud_bullseye_edge_6.1.9.burn.img.xz`
使用`fdisk -l`和`blkid`都看不到移动硬盘,移动硬盘在PC上使用正常.
ntfs和exFAT格式都不可以

**Comment by coffiner** [comment]
供电不足导致

**Comment by hzyitc** [comment]
其他usb设备都能用的话建议检查下供电。
