### ISSUE TITLE
哪个版本支持pppoe直接拨号？能不能做个支持pppoe拨号的版本

### ISSUE THREAD

**Issue by zhouyuyu888** [hzyitc/armbian-onecloud#88]
想让玩客云直接连接光猫pppoe拨号上网，前面下的版本说内核不支持ppp，能不能做一个玩客云可以直接拨号的img?

**Comment by hzyitc** [comment]
直接添加下config吧。我不确定pppoe要开启哪个配置项 。

**Comment by zhouyuyu888** [comment]
我可以添加config打包img吗？因为只用过直接下载的img，没试过添加config生成img的方法。

**Comment by hzyitc** [comment]
修改`config/kernel/linux-meson-edge.config`或者`config/kernel/linux-meson-current.config`，再重新编译即可。
