### ISSUE TITLE
安装mdadm，使用raid0，重启之后系统无法正常启动。

### ISSUE THREAD

**Issue by fvlw** [hzyitc/armbian-onecloud#9]

**Comment by hzyitc** [comment]
请贴出`启动日志`

以及`RAID`是做在什么设备上的，`启动设备`是什么

**Comment by fvlw** [comment]
![图片](https://user-images.githubusercontent.com/71577616/173191178-ba25f956-679d-4d38-9e5a-18b63407f8ec.png)
安装mdadm的日志

**Comment by fvlw** [comment]
> ![图片](https://user-images.githubusercontent.com/71577616/173191178-ba25f956-679d-4d38-9e5a-18b63407f8ec.png) 安装mdadm的日志

安装完毕后，我没有挂载硬盘，也没有创建raid，reboot系统后，系统就启动不起来了。
![图片](https://user-images.githubusercontent.com/71577616/173191335-02f4d2b7-b58b-43ee-979c-91586c8f7891.png)

我不懂怎么焊ttl的针脚，动手能力很差，无法给出设备启动的ttl输出日志。
[https://github.com/hzyitc/armbian-onecloud/releases/download/pr-ci-20220609-1958/Armbian_22.08.0-trunk_Onecloud_bullseye_current_5.14.21.img.xz](用的是这个最新的镜像，不带视频输出和vpu)

**Comment by hzyitc** [comment]
![image](https://user-images.githubusercontent.com/25414097/173193289-1fbdeda7-6519-4be5-8a83-88a14a707533.png)

更新initrd失败

**Comment by fvlw** [comment]
> ![image](https://user-images.githubusercontent.com/25414097/173193289-1fbdeda7-6519-4be5-8a83-88a14a707533.png)
> 
> 更新initrd失败

这属于mdadm的问题，还是armbian的问题，还是我的问题，应该怎么修复？

**Comment by hzyitc** [comment]
`fat`的问题，我研究下吧

**Comment by hzyitc** [comment]
抱歉，刚才误判了。`update-initramfs`那个失败的`ln`是备份。生成`initrd`是正常的

**Comment by hzyitc** [comment]
你是直接u盘启动还是刷入emmc了

**Comment by hzyitc** [comment]
我用我自己本地编译的版本无法复现

**Comment by fvlw** [comment]
[使用这个老哥的u盘启动脚本](https://github.com/hzyitc/armbian-onecloud/files/8876513/s805_autoscript.zip)
[写入emmc使用的是这个帖子镜像提取的脚本](https://www.right.com.cn/forum/thread-8237343-1-1.html)
[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)

**Comment by soulant** [comment]
建议你重新制作U盘系统后，不安装到EMMC，然后在U盘系统下安装mdadm测试，安装重启是否能进U盘系统
1、如无法启动，证明你安装mdadm时，重新生成的uInitrd时已经在系统中无法正常加载，导致启动异常；
2、若启动正常，证明生成uInitrd对后续启动无影响，即刷入EMMC后导致启动异常；

因为你没有TTL日志，只能作如下分析：
由于你刷入EMMC时，此脚本会更改系统当前uboot以及全部环境变量，以及替换s805_autoscript，这些操作，只要UBOOT兼容性差就可能导致EMMC启动异常，U盘启动影响不大，只是u盘兼容性差换U盘即可，估计你的原因多半是uboot被替换造成系统无限开机重启，无法正常执行bootcmd引起的

**Comment by soulant** [comment]
你刷入的底包系统在刷入EMMC时已被替换

**Comment by fvlw** [comment]
> 我用我自己本地编译的版本无法复现



> 建议你重新制作U盘系统后，不安装到EMMC，然后在U盘系统下安装mdadm测试，安装重启是否能进U盘系统 1、如无法启动，证明你安装mdadm时，重新生成的uInitrd时已经在系统中无法正常加载，导致启动异常； 2、若启动正常，证明生成uInitrd对后续启动无影响，即刷入EMMC后导致启动异常；
> 
> 因为你没有TTL日志，只能作如下分析： 由于你刷入EMMC时，此脚本会更改系统当前uboot以及全部环境变量，以及替换s805_autoscript，这些操作，只要UBOOT兼容性差就可能导致EMMC启动异常，U盘启动影响不大，只是u盘兼容性差换U盘即可，估计你的原因多半是uboot被替换造成系统无限开机重启，无法正常执行bootcmd引起的

按你说的方式复现了下，我重新下载了最新的[镜像](https://github.com/hzyitc/armbian-onecloud/releases/download/ci-20220611-1633/Armbian_22.08.0-trunk_Onecloud_bullseye_current_5.14.21.img.xz)，使用你提供的启动[脚本](https://github.com/hzyitc/armbian-onecloud/files/8876513/s805_autoscript.zip)，从u盘启动安装mdadm，输出的log与我写入emmc，启动后，安装mdadm输出的日志一样。
![Snipaste_2022-06-12_20-45-06](https://user-images.githubusercontent.com/71577616/173234171-0403973b-d450-45ca-8277-5004bdce1d6b.png)

使用reboot，系统还是无法正常启动。

**Comment by fvlw** [comment]
> 你刷入的底包系统在刷入EMMC时已被替换

不会，使用别人的[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)，不会替换我的[底包](https://github.com/fvlw/armbian-onecloud/blob/readme/%E9%A6%96%E9%80%89%E5%BA%95%E5%8C%85.img)。

**Comment by soulant** [comment]
> > 你刷入的底包系统在刷入EMMC时已被替换
> 
> 不会，使用别人的[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)，不会替换我的[底包](https://github.com/fvlw/armbian-onecloud/blob/readme/%E9%A6%96%E9%80%89%E5%BA%95%E5%8C%85.img)。

我指的底包实际为uboot文件，并非整个系统，而刷底包的目的主要是刷uboot，所以才有各种极小底包
reboot 无法重启，就换个方式安装  | 先卸载引导分区
```
umount /boot
apt-get install mdadm
#先检测下，主要是检测生成的各种文件特别是uInitrd
ls /boot
shutdown -r now
```
# 此时如果能正常启动，再去检测刚才生成的文件

**Comment by fvlw** [comment]
> > > 你刷入的底包系统在刷入EMMC时已被替换
> > 
> > 
> > 不会，使用别人的[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)，不会替换我的[底包](https://github.com/fvlw/armbian-onecloud/blob/readme/%E9%A6%96%E9%80%89%E5%BA%95%E5%8C%85.img)。
> 
> 我指的底包实际为uboot文件，并非整个系统，而刷底包的目的主要是刷uboot，所以才有各种极小底包 reboot 无法重启，就换个方式安装 | 先卸载引导分区
> 
> ```
> umount /boot
> apt-get install mdadm
> #先检测下，主要是检测生成的各种文件特别是uInitrd
> ls /boot
> shutdown -r now
> ```
> 
> # 此时如果能正常启动，再去检测刚才生成的文件

复现成功。
![Snipaste_2022-06-13_09-32-07](https://user-images.githubusercontent.com/71577616/173264078-8f94e18a-355a-4d6a-8d5d-6d342416fdea.png)
![Snipaste_2022-06-13_09-28-55](https://user-images.githubusercontent.com/71577616/173264083-a34f5473-ba09-4ce3-b098-18961ae97376.png)

**Comment by soulant** [comment]
> > > > 你刷入的底包系统在刷入EMMC时已被替换
> > > 
> > > 
> > > 不会，使用别人的[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)，不会替换我的[底包](https://github.com/fvlw/armbian-onecloud/blob/readme/%E9%A6%96%E9%80%89%E5%BA%95%E5%8C%85.img)。
> > 
> > 
> > 我指的底包实际为uboot文件，并非整个系统，而刷底包的目的主要是刷uboot，所以才有各种极小底包 reboot 无法重启，就换个方式安装 | 先卸载引导分区
> > ```
> > umount /boot
> > apt-get install mdadm
> > #先检测下，主要是检测生成的各种文件特别是uInitrd
> > ls /boot
> > shutdown -r now
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # 此时如果能正常启动，再去检测刚才生成的文件
> 
> ![Snipaste_2022-06-13_09-32-07](https://user-images.githubusercontent.com/71577616/173264078-8f94e18a-355a-4d6a-8d5d-6d342416fdea.png) ![Snipaste_2022-06-13_09-28-55](https://user-images.githubusercontent.com/71577616/173264083-a34f5473-ba09-4ce3-b098-18961ae97376.png)
> 
> 可以了，重启可以进入系统了，但是usb启动占用了我一个usb口，这个镜像没有提供写入emmc脚本，我也无法使用raid，老哥能写一个写入emmc脚本给我吗？

继续测试 | 检测生成uInitrd 对其启动影响
```
cp /boot/{uInitrd,.bak}
mkdir -p /test
cp /boot/{initrd.img*,uInitrd} /test
umount /boot
apt-get purge mdadm -y
mv /test/* /boot
apt-get install mdadm
sync
mv /boot/* /test
mount -a
mv -f /test/* /boot
rmdir /test
shutdown -r now
# 重启失败 | 则在PC上将引导分区中的uInitrd删除后，将备份的uInitrd.bak 恢复或复制为uInitrd
# 重启失败 | 证明生成的uInitrd对启动确实有影响 | 一旦安装会刷新uInitrd的其它软件皆可能启动失败
# 重启成功 | 证明生成的uInitrd对启动无明确影响，至于为什么前面普通顺序安装失败，估计就是文件未完全写入
```

**Comment by fvlw** [comment]
> > > > > 你刷入的底包系统在刷入EMMC时已被替换
> > > > 
> > > > 
> > > > 不会，使用别人的[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)，不会替换我的[底包](https://github.com/fvlw/armbian-onecloud/blob/readme/%E9%A6%96%E9%80%89%E5%BA%95%E5%8C%85.img)。
> > > 
> > > 
> > > 我指的底包实际为uboot文件，并非整个系统，而刷底包的目的主要是刷uboot，所以才有各种极小底包 reboot 无法重启，就换个方式安装 | 先卸载引导分区
> > > ```
> > > umount /boot
> > > apt-get install mdadm
> > > #先检测下，主要是检测生成的各种文件特别是uInitrd
> > > ls /boot
> > > shutdown -r now
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > # 此时如果能正常启动，再去检测刚才生成的文件
> > 
> > 
> > ![Snipaste_2022-06-13_09-32-07](https://user-images.githubusercontent.com/71577616/173264078-8f94e18a-355a-4d6a-8d5d-6d342416fdea.png) ![Snipaste_2022-06-13_09-28-55](https://user-images.githubusercontent.com/71577616/173264083-a34f5473-ba09-4ce3-b098-18961ae97376.png)
> > 可以了，重启可以进入系统了，但是usb启动占用了我一个usb口，这个镜像没有提供写入emmc脚本，我也无法使用raid，老哥能写一个写入emmc脚本给我吗？
> 
> 继续测试 | 直接使用你现在的USB系统(已安装mdadm) | 检测生成uInitrd 对其启动影响
> 
> ```
> cp /boot/{uInitrd,.bak}
> mkdir -p /test
> cp /boot/{initrd.img*,uInitrd} /test
> umount /boot
> apt-get purge mdadm -y
> mv /test/* /boot
> apt-get install mdadm
> sync
> mv /boot/* /test
> mount -a
> mv -f $(realpath /test/uInitrd) /test
> mv -f /test/* /boot
> rmdir /test
> shutdown -r now
> # 重启失败 | 则在PC上将引导分区中的uInitrd删除后，将备份的uInitrd.bak 恢复或复制为uInitrd
> # 重启失败 | 证明生成的uInitrd对启动确实有影响 | 一旦安装会刷新uInitrd的其它软件皆可能启动失败
> # 重启成功 | 证明生成的uInitrd对启动无明确影响，至于为什么前面普通顺序安装失败，估计就是文件未完全写入
> # 重启成功 | 你就可以刷入EMMC | 安装时尽量将引导分区卸载，因FAT分区不支持软链接，导致一些问题，只能替换安装
> ```
![1](https://user-images.githubusercontent.com/71577616/173280616-6145da07-f70f-48fb-91be-c8f95159ccdb.png)
![Snipaste_2022-06-13_12-36-17](https://user-images.githubusercontent.com/71577616/173280621-bd65475a-0fdd-4087-a1d4-874b8fee5304.png)
`root@onecloud:~# mv -f $(realpath /test/uInitrd) /test`
`mv: '/test/uInitrd' and '/test/uInitrd' are the same file`

**Comment by fvlw** [comment]
> > > > > > 你刷入的底包系统在刷入EMMC时已被替换
> > > > > 
> > > > > 
> > > > > 不会，使用别人的[写入emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)，不会替换我的[底包](https://github.com/fvlw/armbian-onecloud/blob/readme/%E9%A6%96%E9%80%89%E5%BA%95%E5%8C%85.img)。
> > > > 
> > > > 
> > > > 我指的底包实际为uboot文件，并非整个系统，而刷底包的目的主要是刷uboot，所以才有各种极小底包 reboot 无法重启，就换个方式安装 | 先卸载引导分区
> > > > ```
> > > > umount /boot
> > > > apt-get install mdadm
> > > > #先检测下，主要是检测生成的各种文件特别是uInitrd
> > > > ls /boot
> > > > shutdown -r now
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > # 此时如果能正常启动，再去检测刚才生成的文件
> > > 
> > > 
> > > ![Snipaste_2022-06-13_09-32-07](https://user-images.githubusercontent.com/71577616/173264078-8f94e18a-355a-4d6a-8d5d-6d342416fdea.png) ![Snipaste_2022-06-13_09-28-55](https://user-images.githubusercontent.com/71577616/173264083-a34f5473-ba09-4ce3-b098-18961ae97376.png)
> > > 可以了，重启可以进入系统了，但是usb启动占用了我一个usb口，这个镜像没有提供写入emmc脚本，我也无法使用raid，老哥能写一个写入emmc脚本给我吗？
> > 
> > 
> > 继续测试 | 直接使用你现在的USB系统(已安装mdadm) | 检测生成uInitrd 对其启动影响
> > ```
> > cp /boot/{uInitrd,.bak}
> > mkdir -p /test
> > cp /boot/{initrd.img*,uInitrd} /test
> > umount /boot
> > apt-get purge mdadm -y
> > mv /test/* /boot
> > apt-get install mdadm
> > sync
> > mv /boot/* /test
> > mount -a
> > mv -f $(realpath /test/uInitrd) /test
> > mv -f /test/* /boot
> > rmdir /test
> > shutdown -r now
> > # 重启失败 | 则在PC上将引导分区中的uInitrd删除后，将备份的uInitrd.bak 恢复或复制为uInitrd
> > # 重启失败 | 证明生成的uInitrd对启动确实有影响 | 一旦安装会刷新uInitrd的其它软件皆可能启动失败
> > # 重启成功 | 证明生成的uInitrd对启动无明确影响，至于为什么前面普通顺序安装失败，估计就是文件未完全写入
> > # 重启成功 | 你就可以刷入EMMC | 安装时尽量将引导分区卸载，因FAT分区不支持软链接，导致一些问题，只能替换安装
> > ```
> 
> ![1](https://user-images.githubusercontent.com/71577616/173280616-6145da07-f70f-48fb-91be-c8f95159ccdb.png) ![Snipaste_2022-06-13_12-36-17](https://user-images.githubusercontent.com/71577616/173280621-bd65475a-0fdd-4087-a1d4-874b8fee5304.png) `root@onecloud:~# mv -f $(realpath /test/uInitrd) /test` `mv: '/test/uInitrd' and '/test/uInitrd' are the same file`

![图片](https://user-images.githubusercontent.com/71577616/173280978-1f7a41ee-91f3-4f43-9e78-30a34a404500.png)


重启成功。系统正常启动。写入emmc的话我还是使用我上面的别人的[emmc脚本](https://github.com/fvlw/armbian-onecloud/blob/readme/install.7z)吗？

**Comment by soulant** [comment]
mv 移动文件失败，你用的还是原来的uInitrd，没达到检测目的
你现在将/boot/uInitrd-XXX这个文件重命名为uInitrd
1、如果能启动成功，说明在ext4格式安装mdadm没问题，可直接用原脚本安装，但安装软件时一定要确认uInitrd完全创建成功
怕创建失败，你就对原uInitrd备个份使用，等安装后不使用新uInitrd，而使用备份文件
2、如果你只想系统启动成功，那完全可将引导分区文件复制到非挂载/boot分区(根下空目录挂载点)，当然也可不复制，然后解除/etc/fstab中引导分区挂载，这样你安装软件对引导分区皆不影响
3、如此系统虽能启动，就是不知道对你执行安装的应用有其它影响没有，主要是你写入EMMC后每次都去尝试也没必要，一旦失败就无法启动，又必须通过外部USB系统启动后挂载修改。
4、最终建议：第2步

**Comment by fvlw** [comment]
> mv 移动文件失败，你用的还是原来的uInitrd，没达到检测目的 你现在将/boot/uInitrd-XXX这个文件重命名为uInitrd 1、如果能启动成功，说明在ext4格式安装mdadm没问题，可直接用原脚本安装，但安装软件时一定要确认uInitrd完全创建成功 怕创建失败，你就对原uInitrd备个份使用，等安装后不使用新uInitrd，而使用备份文件 2、如果你只想系统启动成功，那完全可将引导分区文件复制到非挂载/boot分区(根下空目录挂载点)，当然也可不复制，然后解除/etc/fstab中引导分区挂载，这样你安装软件对引导分区皆不影响 3、如此系统虽能启动，就是不知道对你执行安装的应用有其它影响没有，主要是你写入EMMC后每次都去尝试也没必要，一旦失败就无法启动，又必须通过外部USB系统启动后挂载修改。 4、最终建议：第2步

![图片](https://user-images.githubusercontent.com/71577616/173294417-85abd1ba-2000-4eb9-8439-31dc80a398eb.png)
没有/boot/uInitrd-XXX这个文件。

**Comment by soulant** [comment]
不用管了，直接按照第2步使用 | 当然你要分析，就自己分析了
apt-get install mdadm
本来这步安装后/boot/下应有一个真实文件uInitrd-XXX和软链接uInitrd指向前面这个文件
所以你可以从这步分析，然后将真实文件uInitrd-XXX复制到引导分区，这步必须通过其它文件转移，因都是/boot目录
前面步骤主要就是测试这个在ext4格式下生成的真实文件uInitrd-XXX，到底对系统启动有无影响
我发现上方提示延迟更新uInitrd → 结果是你复制代码时把initrd.img*这个文件夹复制漏了，导致未重新生成uInitrd

**Comment by hzyitc** [comment]
`onecloud`的`u-boot`只支持`fat`和`ext2`。

`fat`不支持`符号连接`，但`update-initramfs`会在`ln`失败后自动使用`cp`

**Comment by soulant** [comment]
现在/boot目录下有这个文件uInitrd-xxx，虽然重新生成时有不少警告，你仍可将其重命名为uInitrd后重启测试

**Comment by hzyitc** [comment]
> > `onecloud`的`u-boot`只支持`fat`和`ext2`。
> > `fat`不支持`符号连接`，但`update-initramfs`会在`ln`失败后自动使用`cp`
> 
> 网络问题到底怎么回事呢？为什么空文件测试速度正常，真实文件就不行呢？

我个人觉得大概率是`时钟`问题，只能说重新编译`u-boot`，然后微调`时钟`试试了

**Comment by hzyitc** [comment]
不能直接`mv`，会复制`符号连接`的。一定是失败的。

`mv`好像有个`follow-symbol`选项，具体名字忘了

**Comment by fvlw** [comment]
> 上面目录地址写错了，应该时/boot，不是/test 现在/boot目录下有这个文件uInitrd-xxx，虽然重新生成时有不少警告，你仍可将其重命名为uInitrd后重启测试

`mv -f $(realpath /boot/uInitrd) /test`
`mv -f /test/* /boot`
这样吗？

**Comment by soulant** [comment]
> 

你直接看上面修改的，只需移动新uInitrd即可

**Comment by fvlw** [comment]
> > 
> 
> 你直接看上面修改的，只需移动新uInitrd即可

![图片](https://user-images.githubusercontent.com/71577616/173321177-09f38237-6357-4a14-b068-1010b37ccfd4.png)

测试成功

**Comment by soulant** [comment]
> > > 
> > 
> > 
> > 你直接看上面修改的，只需移动新uInitrd即可
> 
> ![图片](https://user-images.githubusercontent.com/71577616/173321177-09f38237-6357-4a14-b068-1010b37ccfd4.png)
> 
> 测试成功

# 那你可以刷入EMMC了，但是还是不能直接安装涉及更新uInitrd的应用，只能转存安装，否则可能又失败了
用FAT分区直接安装会失败，用EXT4分区安装会成功，证明update-initramfs命令在你设备FAT分区上安装兼容性差，导致文件异常，当然你感兴趣，可以自己再去分析在FAT分区上安装后生成的文件和在EXT4 分区上安装的文件解包对比，不过太复杂了。

**Comment by fvlw** [comment]
> > > > 
> > > 
> > > 
> > > 你直接看上面修改的，只需移动新uInitrd即可
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/71577616/173321177-09f38237-6357-4a14-b068-1010b37ccfd4.png)
> > 测试成功
> 
> 那你可以刷入EMMC了，但是还是不能直接安装涉及更新uInitrd的应用，只能转存安装，否则可能又失败了 用FAT分区直接安装会失败，用EXT4分区安装会成功，证明update-initramfs命令在你设备FAT分区上安装兼容性差，导致文件异常，当然你感兴趣，可以自己再去分析在FAT分区上安装后生成的文件和在EXT4 分区上安装的文件解包对比，不过太复杂了。

也就是说以后更新mdadm我需要umount/boot 吗

**Comment by soulant** [comment]
估计需要 | 因为我测试时，直接安装后系统能直接启动，但也出现了一次直接重启无法正常开机状态，但我重插电源依然能正常启动，当然系统没有用你用的系统版本
所以才让你测试EXT4 下安装是否异常

**Comment by fvlw** [comment]
> 估计需要 | 因为我测试时，直接安装后系统能直接启动，但也出现了一次直接重启无法正常开机状态，但我重插电源依然能正常启动，当然系统没有用你用的系统版本 所以才让你测试EXT4 下安装是否异常

写入emmc正常启动系统

**Comment by fvlw** [comment]
> 以防万一，我确认一下。
> 
> 楼主知道`重启`有可能导致`ip`改变这件事吗

设备`ip`是通过路由web后台查看的，应该不会出现这种低级错误吧。

**Comment by soulant** [comment]
> 以防万一，我确认一下。
> 
> 楼主知道`重启`有可能导致`ip`改变这件事吗

这个问题其实早已反馈给你了 在速度异常中 我就建议你修复MAC 因为dts中你并没有写入获取主板MAC值 导致网卡会随机生成MAC 自然IP每次重启就发生变化

**Comment by soulant** [comment]
> > 估计需要 | 因为我测试时，直接安装后系统能直接启动，但也出现了一次直接重启无法正常开机状态，但我重插电源依然能正常启动，当然系统没有用你用的系统版本 所以才让你测试EXT4 下安装是否异常
> 
> 写入emmc正常启动系统 ,但是当我创建好了raid0 `mdadm --create /dev/md0 --level=raid0 --raid-devices=2 /dev/sda1 /dev/sdb1`,挂载 ，设置fstab，重启系统后，系统就不能正常开机了。 ![图片](https://user-images.githubusercontent.com/71577616/173358305-d8a19aed-870f-42fb-a753-7162527d664c.png)

建议你用U盘系统 登录后挂载emmc根分区后删除 fstab添加启动项 然后关机换上两个硬盘重启后检查mdadm为你分配的设备节点是否和你挂载点一致 多测试几次 不要马上就写入fstab
涉及fstab时必须小心测试 特别是远程

**Comment by soulant** [comment]
以下是安装mdadm后又可能无法重启进入系统的日志 | 因为没有配置/etc/mdadm/mdadm.conf
```
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... mdadm: No arrays found in config file or automatically
done.
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
mdadm: No arrays found in config file or automatically
```
