### ISSUE TITLE
請問可以透過DD刷入大佬最新的固件嗎? 

### ISSUE THREAD

**Issue by sillydanny** [hzyitc/armbian-onecloud#90]
因為每次用"USB_Burning_Tool＂刷機時都需要拆機觸發點才可以刷機。
請問大佬可以把固件存放到/tmp或者外置USB, 用DD刷入到eMMC嗎?

**Comment by hzyitc** [comment]
不用拆机啊。

刷过就可以直接刷了。连接好后，打开软件，再通电就行。

**Comment by hzyitc** [comment]
不用拆机啊。

刷过就可以直接刷了。连接好后，打开软件，再通电就行。
