### ISSUE TITLE
v1.3版的玩客云靠近hdmi口的usb口无法使用，一插入设备系统就挂了

### ISSUE THREAD

**Issue by jacelift** [hzyitc/armbian-onecloud#92]
v1.3版的玩客云靠近hdmi口的usb口无法使用，一插入设备系统就挂了

只有靠网口的USB可以使用

**Comment by hzyitc** [comment]
dmesg有报错吗

**Comment by ihipop** [comment]
我的 1.0版本，刷了最近的 6.1.12, 插入靠近hdmi口的某些设备（主要是几块wlan网卡），带负载使用一段时间（iperf3跑个 1-2min）会导致USB挂掉 现象是 lsusb卡住，接口插入其他usb设备不识别 ，机器重启也会卡住 

简单的其他操作可以。dmesg也没有什么特别信息。

当然这些设备在其他机器上工作是良好的。而且只有靠近hdmi的口特别容易这样。我看到有个补丁 是移除了ACA判断，看来可能是这靠近HDMI的口有什么不符合设计规范的地方在这边？（但是我的机器是 1.0的）

https://github.com/hzyitc/armbian-onecloud/blob/12836d18fe41b9bd6a36ab9d2213d384273d3c35/patch/kernel/archive/meson-6.1/board_onecloud/usb-disable-ACA-check.patch

**Comment by hzyitc** [comment]
ACA是充电相关的。应该不影响。

待深入研究吧。

**Comment by ihipop** [comment]
> ACA是充电相关的。应该不影响。
> 
> 待深入研究吧。

不知道是不是体质问题，今天USB 1-1（靠近HDMI口的） 出现 这种错误了 `usb 1-1: device descriptor read/64, error -110`

**Comment by unknown-o** [comment]
同样遇到相关问题。我将USB声卡插入到USB1，系统有概率无法启动，即在U-BOOT后就直接无法启动。有时可以启动，但网卡灯闪烁异常，有时候启动后出现kernel panic。目前看到此issues将声卡插到USB2接口似乎没出现相关问题

**Comment by ihipop** [comment]
> 同样遇到相关问题。我将USB声卡插入到USB1，系统有概率无法启动，即在U-BOOT后就直接无法启动。有时可以启动，但网卡灯闪烁异常，有时候启动后出现kernel panic。目前看到此issues将声卡插到USB2接口似乎没出现相关问题

看起来是某些设备在USB1上会导致CPU的电压异常 需要改频率提高CPU电压 https://github.com/hzyitc/armbian-onecloud/issues/87
我已经排除是电源问题.我的电源是足瓦的

**Comment by unknown-o** [comment]
> > 同样遇到相关问题。我将USB声卡插入到USB1，系统有概率无法启动，即在U-BOOT后就直接无法启动。有时可以启动，但网卡灯闪烁异常，有时候启动后出现kernel panic。目前看到此issues将声卡插到USB2接口似乎没出现相关问题
> 
> 看起来是某些设备在USB1上会导致CPU的电压异常 需要改频率提高CPU电压 #87 我已经排除是电源问题.我的电源是足瓦的

感谢你的回复，目前我已不再使用USB1接口，我只有一个USB声卡设备，用于配合高灵敏度监控收音器进行简易监控录音
我也确认了我的电源为京东海康威视、大华自营店购买，不存在虚标或不合格情况

**Comment by lanlanpy** [comment]
内存卡启动的这个版本  CI 2023-04-13 03:38:27 UTC(+00:00) Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.10.img  emmc的uboot是hzyitc大佬的最新uboot

然后usb键盘插的靠近hdmi的usb接口，10次估计有8次会导致内核奔溃。。刷机那个usb口不会导致这个问题，，还没进去系统在启动内核阶段就奔溃了

ttl日志如下
[ttl-2023-04-20-14.log](https://github.com/hzyitc/armbian-onecloud/files/11284491/ttl-2023-04-20-14.log)

**Comment by hzyitc** [comment]
> 内存卡启动的这个版本 CI 2023-04-13 03:38:27 UTC(+00:00) Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.10.img emmc的uboot是hzyitc大佬的最新uboot
> 
> 然后usb键盘插的靠近hdmi的usb接口，10次估计有8次会导致内核奔溃。。刷机那个usb口不会导致这个问题，，还没进去系统在启动内核阶段就奔溃了
> 
> ttl日志如下 [ttl-2023-04-20-14.log](https://github.com/hzyitc/armbian-onecloud/files/11284491/ttl-2023-04-20-14.log)

日志贴错了？

只看到个eMMC的崩溃信息和内核调频相关的故障。

**Comment by lanlanpy** [comment]
> > 内存卡启动的这个版本 CI 2023-04-13 03:38:27 UTC(+00:00) Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.10.img emmc的uboot是hzyitc大佬的最新uboot
> > 然后usb键盘插的靠近hdmi的usb接口，10次估计有8次会导致内核奔溃。。刷机那个usb口不会导致这个问题，，还没进去系统在启动内核阶段就奔溃了
> > ttl日志如下 [ttl-2023-04-20-14.log](https://github.com/hzyitc/armbian-onecloud/files/11284491/ttl-2023-04-20-14.log)
> 
> 日志贴错了？
> 
> 只看到个eMMC的崩溃信息和内核调频相关的故障。

没有贴错，靠近HDMI的usb口插着键盘启动就出现这个信息。。是不是拉低电压导致的啊

**Comment by lanlanpy** [comment]
> > 内存卡启动的这个版本 CI 2023-04-13 03:38:27 UTC(+00:00) Armbian_23.05.0-trunk_Onecloud_bullseye_edge_6.2.10.img emmc的uboot是hzyitc大佬的最新uboot
> > 然后usb键盘插的靠近hdmi的usb接口，10次估计有8次会导致内核奔溃。。刷机那个usb口不会导致这个问题，，还没进去系统在启动内核阶段就奔溃了
> > ttl日志如下 [ttl-2023-04-20-14.log](https://github.com/hzyitc/armbian-onecloud/files/11284491/ttl-2023-04-20-14.log)
> 
> 日志贴错了？
> 
> 只看到个eMMC的崩溃信息和内核调频相关的故障。

https://github.com/hzyitc/u-boot-onecloud/issues/6 这个问题会不会也是同样的原因导致的呢，电压没调好导致异常，因为很多人碰到插着usb设备就碰到启动不了系统的@hzyitc

**Comment by hzyitc** [comment]
https://github.com/hzyitc/armbian-onecloud/issues/87#issuecomment-1487475766

目前来看应该就是同款原因。

**Comment by hzyitc** [comment]
> [hzyitc/u-boot-onecloud#6](https://github.com/hzyitc/u-boot-onecloud/issues/6) 这个问题会不会也是同样的原因导致的呢，电压没调好导致异常，因为很多人碰到插着usb设备就碰到启动不了系统的@hzyitc

大概率不是。目前看起来应该是调频驱动有bug，但不确定。

等过段时间吧，我目前定位到大致的范围了，等过段时间发个包你们试试吧。但最近有点个人私事，得下个月。

**Comment by lanlanpy** [comment]
> > [hzyitc/u-boot-onecloud#6](https://github.com/hzyitc/u-boot-onecloud/issues/6) 这个问题会不会也是同样的原因导致的呢，电压没调好导致异常，因为很多人碰到插着usb设备就碰到启动不了系统的@hzyitc
> 
> 
> 
> 大概率不是。目前看起来应该是调频驱动有bug，但不确定。
> 
> 
> 
> 等过段时间吧，我目前定位到大致的范围了，等过段时间发个包你们试试吧。但最近有点个人私事，得下个月。

坐等大佬修复
