### ISSUE TITLE
6.1.12 内核，网卡累积流量 >=2GB后统计异常。

### ISSUE THREAD

**Issue by ihipop** [hzyitc/armbian-onecloud#93]
https://user-images.githubusercontent.com/423077/221075694-e0cab5e4-bf24-4ead-b835-11d2d7385cd7.mp4

会溢出为 163 PB，然后重置循环

`Linux onecloud 6.1.12-meson #trunk SMP Tue Feb 21 13:35:59 UTC 2023 armv7l GNU/Linux`

RX/TX都一样

**Comment by hzyitc** [comment]
![image](https://user-images.githubusercontent.com/25414097/227345641-1f92f682-16ca-4953-951c-609f21ff94b1.png)

`Linux onecloud 6.2.8-meson #1 SMP Wed Mar 22 20:38:11 CST 2023 armv7l GNU/Linux` 下无法复现。

6.1的话，等我有空试试。

**Comment by ABEDC0DE** [comment]
2GB这个无法复现，4GB的复现了，ifconfig是从/proc/net/dev读取的，受限于32位CPU和系统，4GB循环是正常现象，需要查看使用流量建议使用vnstat代替，印象中是默认安装的。

参考资料：
[Bug 469](https://bugzilla.kernel.org/show_bug.cgi?id=469) - `/proc/net/dev byte counter wraps after 2^32`
