### ISSUE TITLE
使用最新armbian官方源编译 img镜像内部使用zimage，而不是uimage，导致无法启动

### ISSUE THREAD

**Issue by lloovve** [hzyitc/armbian-onecloud#96]
使用最新armbian官方源编译 img镜像内部使用zimage，而不是uimage，导致无法启动
编译结果：Armbian_23.05.0-trunk_Onecloud_bullseye_current_6.1.14.img
编译命令：./compile.sh BOARD=onecloud BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=yes COMPRESS_OUTPUTIMAGE=sha,img
其他说明：修改完内核配置文件后重新编译内核
经查好像是：generate-uImage-instand-of-zImage.patch 这个补丁没有生效

**Comment by hzyitc** [comment]
暂时先使用`master`分支进行编译。

`main`分支是`armbian-next`，上游刚切换不久，我还没修复。

**Comment by lloovve** [comment]
ok armbian官方仓库测试master 编译正常

**Comment by Jiang-Xinyu** [comment]
大佬，啥时候能修复呢？或者，我们能自己修改吗？

**Comment by hzyitc** [comment]
> 大佬，啥时候能修复呢？或者，我们能自己修改吗？

修了啊。 只是上游还没合并。
