### ISSUE TITLE
Hi 大佬，能为赚钱宝pro也Build一个Armbian的包吗？

### ISSUE THREAD

**Issue by jeremy-jm** [hzyitc/armbian-onecloud#98]
Hi 大佬 @hzyitc ，能为赚钱宝pro也Build一个Armbian的包吗？

赚钱宝Pro，赚钱宝2代，型号：ws1508

512 Mb + 4G 百兆网口的，功耗非常低，1.8～2.4W的样子，不挂U盘等。百兆平时基本够用。

**Comment by hzyitc** [comment]
本人没有相关硬件，没法测试。
