### ISSUE TITLE
玩客云刷完armbian后自身上传速度极低

### ISSUE THREAD

**Issue by k3bc999** [hzyitc/armbian-onecloud#99]
做旁路由时发现网速下降极为严重，于是用iperf3测了一下与局域网中另一台windows设备的通信速度

发现当玩客云做客户端时，也就是上传时速度极低，自身做服务端，下载时速度倒是隐约能到千兆
想问一下这是我这台玩客云不太行了，还是说通病

![image](https://user-images.githubusercontent.com/27000015/222454016-db305e5e-9988-48fe-a911-1c02e0f79bf7.png)

**Comment by hzyitc** [comment]
#2 

V1.3用目前的kernel，可能都会。
